// =============================================================================
// DungeonMultiLevelRegression — pins the VERTICAL (multi-level) dungeon contract.
// -----------------------------------------------------------------------------
// WO-1001 slice 1. A "deep dungeon" is a DESCENT: floors stacked in Y, joined by
// StairDown -> StairUp socket pairs. Before this slice that was impossible, and
// impossible in a way no oracle noticed, because three independent things each
// silently forbade it:
//
//   1. BOTH stair sockets pointed DOWN and sat at local Y = 0, so a StairUp/
//      StairDown pair scored align = -1 against a +0.25 threshold. They could
//      never mate, and carried no height to mate ACROSS.
//   2. TryMate's corrective nudge was planar-only, so a Y gap could never close
//      and reported MateFailReason.Distance forever.
//   3. RoomsOverlap was XZ-only, so a CORRECTLY stacked pair - whose footprints
//      coincide completely by design - was reported as an overlap, which is a
//      hard bake abort.
//
// Any one of those reverting silently re-breaks multi-level dungeons while every
// existing suite stays green, so each gets a case here.
//
// Case 5 is the one that earns its keep: the room prefabs are GENERATED by
// DefaultDungeonRoomsBuilder, so editing that builder changes nothing on disk
// until "Defenders/Dungeon/Build Default Room Prefabs" is re-run. Case 5 reads
// the actual prefab assets, so a builder edit that was never baked into the
// prefabs fails loudly instead of looking fixed.
// =============================================================================

using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;
using DeNelle.Dungeons.RoomForge;

namespace DeNelle.Editor.Regression
{
    public static class DungeonMultiLevelRegression
    {
        private const string StairDownPrefab = "Assets/Dungeon/Rooms/StairDown.prefab";
        private const string StairUpPrefab = "Assets/Dungeon/Rooms/StairUp.prefab";
        private const float MaxD = 1.25f;

        private static readonly List<GameObject> s_spawned = new List<GameObject>();

        /// <summary>Standalone batch entry — prints the DUNGEON_MULTILEVEL_OK/_FAIL marker.</summary>
        public static void RunAll()
        {
            if (Run(out string reason)) Debug.Log("DUNGEON_MULTILEVEL_OK - " + reason);
            else Debug.LogError("DUNGEON_MULTILEVEL_FAIL: " + reason);
        }

        /// <summary>Covenant contract for DataRegression.RunAll ([dungeon-multilevel]). Never throws.</summary>
        public static bool Run(out string reason)
        {
            var failures = new List<string>();
            try
            {
                Case(failures, "oppose", () => Case1_StairSocketsOppose(failures));
                Case(failures, "floor-drop", () => Case2_FloorDrop(failures));
                Case(failures, "stack-not-overlap", () => Case3_StackIsNotOverlap(failures));
                Case(failures, "door-planar", () => Case4_DoorsKeepPlanarNudge(failures));
                Case(failures, "prefab-poses", () => Case5_PrefabsCarryThePoses(failures));
                Case(failures, "vertical-seal", () => Case6_UnmatedStairSealsInvisibly(failures));
            }
            finally
            {
                Cleanup();
            }

            if (failures.Count == 0)
            {
                reason = "DUNGEON-MULTILEVEL OK - 6/6 cases pass (stair sockets oppose, " +
                         $"floor drop == {DungeonBakerChecks.FloorSeparationY:0}u, stacked rooms are not " +
                         "an overlap, doors keep the planar-only nudge, shipped stair prefabs carry the poses, " +
                         "unmated stair sockets seal invisibly)";
                return true;
            }
            reason = "DUNGEON-MULTILEVEL FAIL x" + failures.Count + ": " + string.Join(" | ", failures);
            return false;
        }

        // =====================================================================
        //  CASE 1 — a StairDown/StairUp pair OPPOSES (and the old pose does not)
        // =====================================================================
        private static void Case1_StairSocketsOppose(List<string> failures)
        {
            float h = DungeonBakerChecks.FloorSeparationY * 0.5f;

            // Upper room's StairDown leads down; lower room's StairUp leads up.
            var upper = MakeRoom("ML_upper", StairSock("stair_down_01", RoomSocketType.StairDown, -h, Vector3.down));
            var lower = MakeRoom("ML_lower", StairSock("stair_up_01", RoomSocketType.StairUp, h, Vector3.up));
            Place(upper, Vector3.zero, 0f);
            Place(lower, new Vector3(0f, -DungeonBakerChecks.FloorSeparationY, 0f), 0f);

            var r = DungeonBakerChecks.TryMate(Sk(upper, "stair_down_01"), Sk(lower, "stair_up_01"), lower, MaxD);
            if (!r.ok)
                failures.Add($"[oppose] a stacked StairDown/StairUp pair MUST mate (ok={r.ok} reason={r.reason} dist={r.dist:F2} align={r.align:F2})");

            // The pre-WO-1001 authoring: BOTH sockets pointing down at local Y=0. This must still
            // fail, otherwise the alignment gate has been loosened and any two stair rooms would
            // mate in any orientation.
            var oldA = MakeRoom("ML_oldA", StairSock("stair_down_01", RoomSocketType.StairDown, 0f, Vector3.down));
            var oldB = MakeRoom("ML_oldB", StairSock("stair_up_01", RoomSocketType.StairUp, 0f, Vector3.down));
            Place(oldA, Vector3.zero, 0f);
            Place(oldB, Vector3.zero, 0f);
            var old = DungeonBakerChecks.TryMate(Sk(oldA, "stair_down_01"), Sk(oldB, "stair_up_01"), oldB, MaxD);
            if (old.ok)
                failures.Add($"[oppose] two DOWN-facing stair sockets must NOT mate - the alignment gate has been loosened (align={old.align:F2})");

            // Type compatibility is what lets the pair be considered at all.
            if (!DungeonBakerChecks.TypesCompatible(RoomSocketType.StairDown, RoomSocketType.StairUp))
                failures.Add("[oppose] StairDown/StairUp are no longer type-compatible");
            if (DungeonBakerChecks.TypesCompatible(RoomSocketType.Door, RoomSocketType.StairDown))
                failures.Add("[oppose] a Door must never mate a stair socket");
            if (!DungeonBakerChecks.IsVertical(RoomSocketType.StairUp) ||
                !DungeonBakerChecks.IsVertical(RoomSocketType.StairDown) ||
                DungeonBakerChecks.IsVertical(RoomSocketType.Door))
                failures.Add("[oppose] IsVertical must be true for stairs and false for doors");
        }

        // =====================================================================
        //  CASE 2 — the socket poses encode exactly one floor of drop
        // =====================================================================
        private static void Case2_FloorDrop(List<string> failures)
        {
            float sep = DungeonBakerChecks.FloorSeparationY;
            float h = sep * 0.5f;

            // This mirrors GraphDungeonComposer.SolveMate's position solve for a vertical mate:
            // yaw stays 0, so pos = parentSocketWorld - childSocketLocal. The whole point of
            // splitting the separation across the two sockets is that this lands one floor down
            // with no elevation field anywhere in the graph schema.
            var upper = MakeRoom("ML_drop_upper", StairSock("stair_down_01", RoomSocketType.StairDown, -h, Vector3.down));
            Place(upper, Vector3.zero, 0f);
            var lower = MakeRoom("ML_drop_lower", StairSock("stair_up_01", RoomSocketType.StairUp, h, Vector3.up));
            Place(lower, Vector3.zero, 0f);   // at identity, so socket world == local

            Vector3 pSock = Sk(upper, "stair_down_01").WorldPosition;
            Vector3 cLocal = Sk(lower, "stair_up_01").transform.position;
            Vector3 solved = pSock - cLocal;

            if (Mathf.Abs(solved.y + sep) > 0.001f)
                failures.Add($"[floor-drop] solved child Y expected {-sep:0.###}, got {solved.y:0.###} - the stair sockets no longer encode half a floor each");
            if (Mathf.Abs(solved.x) > 0.001f || Mathf.Abs(solved.z) > 0.001f)
                failures.Add($"[floor-drop] a vertical mate must not drift on XZ (got x={solved.x:0.###} z={solved.z:0.###})");

            // And the drop must be big enough to clear the room walls, or floors interpenetrate.
            const float WallHeight = 2.8f;   // DefaultDungeonRoomsBuilder.BuildPerimeterWalls
            if (sep <= WallHeight)
                failures.Add($"[floor-drop] FloorSeparationY {sep:0.##} does not clear the {WallHeight:0.##}u walls - stacked floors would interpenetrate");
        }

        // =====================================================================
        //  CASE 3 — a correct vertical stack is NOT an overlap; same floor still is
        // =====================================================================
        private static void Case3_StackIsNotOverlap(List<string> failures)
        {
            var a = MakeRoom("ML_ov_a");
            var b = MakeRoom("ML_ov_b");
            var ma = a.GetComponent<RoomPrefabMeta>();
            var mb = b.GetComponent<RoomPrefabMeta>();
            float sep = DungeonBakerChecks.FloorSeparationY;
            float tol = DungeonBakerChecks.OverlapTolerance;

            // Identical footprint, one floor apart - the stairwell case. Must NOT be an overlap.
            if (DungeonBakerChecks.RoomsOverlap(ma, Vector3.zero, 0f, mb, new Vector3(0f, -sep, 0f), 0f, tol))
                failures.Add("[stack-not-overlap] rooms one floor apart were reported as overlapping - this aborts every multi-level bake");

            // Same position, same floor - still a real overlap. The Y escape hatch must not
            // have blinded the check for coplanar rooms.
            if (!DungeonBakerChecks.RoomsOverlap(ma, Vector3.zero, 0f, mb, Vector3.zero, 0f, tol))
                failures.Add("[stack-not-overlap] two rooms at the SAME position must still overlap");

            // A small Y jitter on one floor must not be mistaken for a second floor.
            if (!DungeonBakerChecks.RoomsOverlap(ma, Vector3.zero, 0f, mb, new Vector3(0f, 0.4f, 0f), 0f, tol))
                failures.Add("[stack-not-overlap] a 0.4u Y jitter is not a floor change - the rooms still overlap");

            // Side by side on the same floor - a shared wall, not an overlap (unchanged contract).
            if (DungeonBakerChecks.RoomsOverlap(ma, Vector3.zero, 0f, mb, new Vector3(6f, 0f, 0f), 0f, tol))
                failures.Add("[stack-not-overlap] adjacent rooms sharing a wall must not count as overlapping");
        }

        // =====================================================================
        //  CASE 4 — doors keep the PLANAR-only nudge (a Y gap is still an error)
        // =====================================================================
        private static void Case4_DoorsKeepPlanarNudge(List<string> failures)
        {
            // The 3D nudge is scoped to stair pairs on purpose. If it were applied to doors, a
            // room authored at the wrong height would be silently lifted to hide the mistake
            // instead of failing the bake.
            var a = MakeRoom("ML_door_a", Sock("n", RoomSocketType.Door, new Vector3(0, 0, 3), Vector3.forward));
            var b = MakeRoom("ML_door_b", Sock("s", RoomSocketType.Door, new Vector3(0, 0, -3), Vector3.back));
            Place(b, new Vector3(0, 3f, 6), 0f);   // 3u vertical gap between two DOORS

            var r = DungeonBakerChecks.TryMate(Sk(a, "n"), Sk(b, "s"), b, MaxD);
            if (r.ok || r.reason != MateFailReason.Distance)
                failures.Add($"[door-planar] a door pair with a 3u Y gap must FAIL on distance, not be lifted into place (ok={r.ok} reason={r.reason} dist={r.dist:F2})");
            if (Mathf.Abs(b.transform.position.y - 3f) > 0.001f)
                failures.Add($"[door-planar] the door nudge moved the room in Y (y={b.transform.position.y:0.###}) - it must stay planar");
        }

        // =====================================================================
        //  CASE 5 — the SHIPPED stair prefabs actually carry the poses
        // =====================================================================
        private static void Case5_PrefabsCarryThePoses(List<string> failures)
        {
            float h = DungeonBakerChecks.FloorSeparationY * 0.5f;
            CheckStairPrefab(failures, StairDownPrefab, "stair_down_01", RoomSocketType.StairDown, -h, Vector3.down);
            CheckStairPrefab(failures, StairUpPrefab, "stair_up_01", RoomSocketType.StairUp, h, Vector3.up);
        }

        private static void CheckStairPrefab(List<string> failures, string path, string socketId,
                                             RoomSocketType expectType, float expectY, Vector3 expectOutward)
        {
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
            if (prefab == null)
            {
                failures.Add($"[prefab-poses] {path} does not load - room prefab library missing or renamed");
                return;
            }

            var sock = DungeonBakerChecks.FindSocket(prefab, socketId);
            if (sock == null)
            {
                failures.Add($"[prefab-poses] {path} has no socket '{socketId}'");
                return;
            }
            if (sock.type != expectType)
                failures.Add($"[prefab-poses] {path} socket '{socketId}' type is {sock.type}, expected {expectType}");

            float y = sock.transform.localPosition.y;
            if (Mathf.Abs(y - expectY) > 0.01f)
                failures.Add($"[prefab-poses] {path} socket '{socketId}' local Y is {y:0.###}, expected {expectY:0.###}. " +
                             "The generated prefabs are STALE - re-run Defenders/Dungeon/Build Default Room Prefabs " +
                             "(DefaultDungeonRoomsBuilder.BuildAll) after editing the builder.");

            // transform.forward is what RoomSocket.Outward returns and what the mate test reads.
            float dot = Vector3.Dot(sock.transform.forward.normalized, expectOutward);
            if (dot < 0.99f)
                failures.Add($"[prefab-poses] {path} socket '{socketId}' points {sock.transform.forward}, expected {expectOutward} " +
                             $"(dot={dot:0.###}). Stale prefabs - re-run DefaultDungeonRoomsBuilder.BuildAll.");
        }

        // =====================================================================
        //  CASE 6 — an UNMATED stair socket seals invisibly, not as a floating slab
        // =====================================================================
        private static void Case6_UnmatedStairSealsInvisibly(List<string> failures)
        {
            float h = DungeonBakerChecks.FloorSeparationY * 0.5f;

            // dg_starter_loop has StairUp/StairDown rooms whose stair sockets are in NO edge, so
            // they get sealed. A wall slab is meaningless on a floor hole at any height, and once
            // slice 1 moved the socket half a floor up it would hang in mid-air in a room the
            // owner actually plays. Must be an invisible marker.
            var up = MakeRoom("ML_seal_up", StairSock("stair_up_01", RoomSocketType.StairUp, h, Vector3.up));
            var sock = Sk(up, "stair_up_01");
            bool spawnedGeometry = DungeonBakerChecks.SealSocket(sock);

            if (spawnedGeometry)
                failures.Add("[vertical-seal] an unmated stair socket spawned wall geometry - it would float half a floor up");
            if (sock.matedTo != "SEALED_VERTICAL")
                failures.Add($"[vertical-seal] expected matedTo=SEALED_VERTICAL, got '{sock.matedTo}' - the seal kind must stay distinguishable from SECRET in the bake trace");
            if (sock.transform.childCount != 0)
                failures.Add($"[vertical-seal] the stair socket gained {sock.transform.childCount} child object(s) - an invisible seal must spawn nothing");

            // A normal unmated DOOR must still get its wall - this fix must not blank real walls.
            var room = MakeRoom("ML_seal_door", Sock("n", RoomSocketType.Door, new Vector3(0, 0, 3), Vector3.forward));
            var door = Sk(room, "n");
            if (!DungeonBakerChecks.SealSocket(door))
                failures.Add("[vertical-seal] an unmated DOOR must still be sealed with wall geometry");
            if (door.matedTo != "SEALED_WALL")
                failures.Add($"[vertical-seal] door seal expected matedTo=SEALED_WALL, got '{door.matedTo}'");

            // And a secret socket must still seal invisibly (unchanged contract).
            var secretRoom = MakeRoom("ML_seal_secret", Sock("s", RoomSocketType.Door, new Vector3(0, 0, -3), Vector3.back));
            var sec = Sk(secretRoom, "s");
            sec.isSecret = true;
            if (DungeonBakerChecks.SealSocket(sec))
                failures.Add("[vertical-seal] a secret socket must not spawn wall geometry");
            if (sec.matedTo != "SEALED_SECRET")
                failures.Add($"[vertical-seal] secret seal expected matedTo=SEALED_SECRET, got '{sec.matedTo}'");
        }

        // -------- helpers --------

        private struct SockSpec
        {
            public string id;
            public RoomSocketType type;
            public Vector3 local;
            public Vector3 outward;
        }

        private static SockSpec Sock(string id, RoomSocketType type, Vector3 local, Vector3 outward)
            => new SockSpec { id = id, type = type, local = local, outward = outward };

        // A stair socket: on the room's vertical axis, half a floor off the origin.
        private static SockSpec StairSock(string id, RoomSocketType type, float localY, Vector3 outward)
            => new SockSpec { id = id, type = type, local = new Vector3(0f, localY, 0.5f), outward = outward };

        private static GameObject MakeRoom(string id, params SockSpec[] socks)
        {
            var go = new GameObject(id);
            s_spawned.Add(go);
            var meta = go.AddComponent<RoomPrefabMeta>();
            meta.roomId = id;
            meta.archetype = "hub";
            meta.cellSize = 6f;
            meta.footprintCells = Vector2Int.one;
            foreach (var s in socks)
            {
                var sg = new GameObject("Socket_" + s.id);
                sg.transform.SetParent(go.transform, false);
                sg.transform.localPosition = s.local;
                Vector3 fwd = s.outward.sqrMagnitude > 0.0001f ? s.outward : Vector3.forward;
                // Explicit up-vector: LookRotation(up) / LookRotation(down) alone is degenerate
                // against the default world up and yields an arbitrary roll.
                Vector3 up = Mathf.Abs(Vector3.Dot(fwd.normalized, Vector3.up)) > 0.99f
                    ? Vector3.forward
                    : Vector3.up;
                sg.transform.localRotation = Quaternion.LookRotation(fwd, up);
                var rs = sg.AddComponent<RoomSocket>();
                rs.id = s.id;
                rs.type = s.type;
                rs.halfWidth = 1.2f;
            }
            return go;
        }

        private static void Place(GameObject go, Vector3 pos, float yaw)
        {
            go.transform.position = pos;
            go.transform.rotation = Quaternion.Euler(0f, yaw, 0f);
        }

        private static RoomSocket Sk(GameObject room, string id) => DungeonBakerChecks.FindSocket(room, id);

        // Guard each case so one throw becomes a labelled failure, not a dead suite.
        private static void Case(List<string> failures, string name, Action body)
        {
            try { body(); }
            catch (Exception ex) { failures.Add($"[{name}] THREW {ex.GetType().Name}: {ex.Message}"); }
        }

        private static void Cleanup()
        {
            foreach (var go in s_spawned) if (go != null) UnityEngine.Object.DestroyImmediate(go);
            s_spawned.Clear();
        }
    }
}
