using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEngine;

namespace DeNelle.Editor
{
    /// <summary>Generates the WO-1170 site-2 runtime fallback from canonical JSON.</summary>
    public static class BuildCategoryFallbackGenerator
    {
        public const string MarkerOk = "BUILD_CATEGORY_FALLBACK_GEN_OK";
        public const string MarkerFail = "BUILD_CATEGORY_FALLBACK_GEN_FAIL";
        public const string ResourcesCopy = "Assets/Resources/Data/Canonical/build-categories.json";
        public const string StreamingCopy = "Assets/StreamingAssets/Data/Canonical/build-categories.json";
        public const string OutputPath = "Assets/_Modules/Village/Catalog/Generated/BuildCategoryFallbackData.g.cs";
        public const string RegenCommand = "powershell -NoProfile -File .\\run-unity-method.ps1 -Method DeNelle.Editor.BuildCategoryFallbackGenerator.Generate -LogName build-category-fallback-gen.log -ExpectMarker BUILD_CATEGORY_FALLBACK_GEN_OK";

        [MenuItem("Defenders/Catalog/Regenerate Build Category Fallback (WO-1170)")]
        public static void Generate()
        {
            try
            {
                byte[] resources = ReadRequired(ResourcesCopy);
                byte[] streaming = ReadRequired(StreamingCopy);
                string hash = Sha256(resources);
                if (!string.Equals(hash, Sha256(streaming), StringComparison.Ordinal))
                    throw new InvalidDataException("canonical Resources and StreamingAssets copies are not byte-identical");

                string json = new UTF8Encoding(false, true).GetString(resources);
                JObject root = JObject.Parse(json);
                JArray rows = root["categories"] as JArray;
                if (rows == null || rows.Count == 0)
                    throw new InvalidDataException("canonical JSON has no non-empty categories array");

                // Embed only runtime schema fields. Authoring notes remain canonical and are
                // still covered by SourceSha256, but need not occupy player metadata.
                var runtime = new JObject
                {
                    ["version"] = root["version"]?.DeepClone(),
                    ["categories"] = rows.DeepClone(),
                };
                string compact = runtime.ToString(Formatting.None);
                string base64 = Convert.ToBase64String(Encoding.UTF8.GetBytes(compact));
                string source = BuildSource(base64, hash, resources.Length, rows.Count,
                    root["version"] != null ? (int)root["version"] : 0);
                string absolute = Path.Combine(Directory.GetCurrentDirectory(), OutputPath.Replace('/', Path.DirectorySeparatorChar));
                Directory.CreateDirectory(Path.GetDirectoryName(absolute));
                File.WriteAllBytes(absolute, new UTF8Encoding(false).GetBytes(source));
                AssetDatabase.ImportAsset(OutputPath, ImportAssetOptions.ForceUpdate);
                Debug.Log($"{MarkerOk} rows={rows.Count} bytes={resources.Length} sha256={hash} output={OutputPath}");
            }
            catch (Exception ex)
            {
                Debug.LogError($"{MarkerFail} {ex.GetType().Name}: {ex.Message}");
            }
        }

        private static byte[] ReadRequired(string path)
        {
            string absolute = Path.Combine(Directory.GetCurrentDirectory(), path.Replace('/', Path.DirectorySeparatorChar));
            if (!File.Exists(absolute)) throw new FileNotFoundException("canonical input is missing", path);
            return File.ReadAllBytes(absolute);
        }

        private static string Sha256(byte[] bytes)
        {
            using (SHA256 sha = SHA256.Create())
            {
                byte[] hash = sha.ComputeHash(bytes);
                var text = new StringBuilder(hash.Length * 2);
                foreach (byte value in hash) text.Append(value.ToString("x2"));
                return text.ToString();
            }
        }

        private static string BuildSource(string base64, string hash, int bytes, int rows, int version)
        {
            return "// <auto-generated> DO NOT EDIT. Generated from build-categories.json. </auto-generated>\n" +
                   "using System;\nusing System.Text;\n\nnamespace DeNelle.Village\n{\n" +
                   "    public static class BuildCategoryFallbackData\n    {\n" +
                   $"        public const string SourceSha256 = \"{hash}\";\n" +
                   $"        public const int SourceByteLength = {bytes};\n" +
                   $"        public const int SourceCategoryCount = {rows};\n" +
                   $"        public const int SourceVersion = {version};\n" +
                   $"        public const string RegenerateCommand = \"{RegenCommand.Replace("\\", "\\\\")}\";\n" +
                   $"        private const string Base64 = \"{base64}\";\n" +
                   "        private static string _json;\n" +
                   "        public static string Json => _json ?? (_json = Encoding.UTF8.GetString(Convert.FromBase64String(Base64)));\n" +
                   "    }\n}\n";
        }
    }
}
