// =============================================================================
// HeroAnimatorFactory — builds per-class hero AnimatorControllers from the
// Mixamo clips in Assets/Action/ (WO-140). Replaces the obsolete Tripo-era
// HeroAnimatorSetup (which scraped 2 generic NLA takes per FBX).
// -----------------------------------------------------------------------------
// Data-driven: ONE Build(HeroSpec) algorithm consumes a per-class spec, so the
// three heroes are three spec literals (not three code paths) — refactor-ready
// toward a shared AnimatorBuildSpec when the catalog grows (NOT a meta-factory;
// see WO-140). NOT recursive: a controller is a flat state list + a blend tree.
//
// Runtime contract (verified in HeroLocomotion/HeroAbilities, 2026-05-30):
//   Speed   (float)   — HeroLocomotion sets = velocity magnitude → Idle/Walk/Run
//   Cast    (trigger) — HeroAbilities.TryCast → the class attack
//   Victory (trigger) — HeroLocomotion on wave clear → victory pose
// Controllers load via Resources.Load("Heroes/<slug>") where slug ∈
// {Knight, Ranger, Mage}; output paths are fixed at Resources/Heroes/<slug>.controller.
//
// Clips are Humanoid (Assets/Action are animationType 3 + CreateFromThisModel),
// so one clip retargets onto every hero. Every clip lookup is null-guarded — a
// missing FBX logs a warning and skips that state; the build still completes.
// =============================================================================
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

namespace DeNelle.Editor
{
    public static class HeroAnimatorFactory
    {
        // WO-283: clips now live in per-type subfolders under Assets/Action/. Each
        // hero searches its type folder first, then Shared/ (the base set every model
        // retargets). ActionDir kept for the legacy flat-folder fallback.
        private const string ActionDir = "Assets/Action/";
        private const string SharedDir = "Assets/Action/Shared/";

        // ── WO-217 / WO-218 tuning ───────────────────────────────────────────
        // Attack/cast snappiness (WO-217): play the swing faster + recover quick.
        // Lowered exit times for "attack fast with animation cycles" on rapid button
        // presses (especially important for Ranger archer aim/fire cycles while the
        // OTS camera is surveying and targeting). The clip plays the cycle, then
        // quickly returns to ready/locomotion so the next press feels immediate.
        private const float AttackSpeed  = 1f;     // authored 1.0x (owner "go with defaults" 2026-07-03; was 1.3f WO-217 snappy-swing — mocap plays at natural speed)
        private const float CastExitTime = 0.38f;  // quick return for fast re-trigger / cycle chaining
        private const float CastExitDur  = 0.03f;  // very tight blend back to ready pose
        // Upper-body attack layer (WO-218): lets the hero swing/cast while moving.
        // Mask generated by EnsureUpperBodyMask(); arms+torso enabled, legs+root off.
        private const string UpperMaskPath = "Assets/Generated/Animators/HeroUpperBody.mask";
        // WO-218: Speed threshold (raw world u/s) below which the hero is "standing".
        // The BASE-layer Cast/Attack (full-body swing) only fires when standing; while
        // MOVING the base layer STAYS in Locomotion (legs keep walking/running) and the
        // upper-body layer alone carries the swing — so the attack no longer freezes the
        // legs. Tuned below the walk centre (6) so any real locomotion gates the full
        // -body version. Idle/near-idle (< this) still plays the clean full-body attack.
        private const float StandingSpeedMax = 2.0f;

        // Shared locomotion clips (all classes) — canonical WO-283 Shared/ basenames.
        private const string IdleClip      = "Shared_Idle";
        private const string WalkClip      = "Shared_Walk_Forward";
        private const string RunClip       = "Shared_Run_Forward";
        private const string VictoryClip   = "Shared_Victory_Pose";

        // WO-284/285 shared combat clips — every hero retargets these from Shared/.
        private const string HitClip       = "Shared_Hit_Reaction";
        private const string DeathClip     = "Shared_Death";
        private const string BlockClip     = "Shared_Block";

        // WO-493 #5 / WO-497: HERO injured-stance locomotion. Reuses the same retargetable
        // Humanoid injured clips the ENEMY half uses (Assets/Action/Enemies/injured*.fbx) —
        // a wounded idle/limp/stagger sub-tree entered when the Injured bool is set (the
        // hero drops below ~30% HP; HeroHealth drives ActorAnimator.SetInjured). Mirrors
        // BuildOrcHumanoidController's InjuredLocomotion swap. Null-guarded: a missing clip
        // falls back to the healthy locomotion so the state is never empty.
        private static readonly string[] InjuredRoots = { "Assets/Action/Enemies/" };
        // Injured IDLE upgraded 2026-07-03: "injured hurting idle" (hurt-but-standing, clutching
        // the wound, rooted) replaces the flat "injured idle" placeholder — cleaner wounded read.
        // Same Humanoid mixamo rig (animationType:3) so it retargets onto the hero avatar exactly
        // like the old clip; null-guarded fallback to healthy idle is unchanged.
        private const string InjuredIdleClip = "injured hurting idle";
        private const string InjuredWalkClip = "injured walk";
        private const string InjuredRunClip  = "injured run";

        // Directional death clips (DeathDir int: 0=Fall/centre, 1=Left, 2=Right). When
        // present, a "Death1"/"Death2" state is gated on Dead==true AND DeathDir==N so a
        // hit from the side topples the right way; the plain Death covers DeathDir 0.
        private const string DeathLeftClip  = "Shared_Standing_Death_Left";
        private const string DeathRightClip = "Shared_Standing_Death_Right";

        private struct HeroSpec
        {
            public string slug;            // Knight | Ranger | Mage | Cleric
            public string controllerPath;  // Resources/Heroes/<slug>.controller
            public string castClip;        // per-class spell/cast clip basename (the generic / variant-0 cast)
            public string castClipFallback;// used + warned if the primary is absent
            public string[] attackClips;   // WO-285: melee combo (Knight = 3, else 1)
            public string[] searchRoots;   // WO-283: type folder first, then Shared/

            // PER-SPELL CASTS: one clip per ability slot, indexed by CastVariant 1..4
            // (q/w/e/r). HeroAbilities.TryCast(slot) fires Cast with CastVariant = slot+1,
            // so the matching CastN state plays that spell's own animation. Index 0 is
            // unused/ignored (variant 0 = the generic `castClip` state). A null/missing
            // entry is skipped (that slot falls back to the generic Cast). Length may be
            // < 5; only the present indices build states.
            public string[] spellCastClips;
        }

        // WO-283 §1 type->folder mapping. Casters (Mage + Cleric) share the Wizard set.
        private static readonly string[] KnightRoots = { "Assets/Action/Knight/",  SharedDir };
        private static readonly string[] RangerRoots = { "Assets/Action/Ranger/",  SharedDir };
        private static readonly string[] WizardRoots = { "Assets/Action/Wizard/",  SharedDir };

        private static readonly HeroSpec[] Specs =
        {
            new HeroSpec { slug = "Knight",
                controllerPath = "Assets/Resources/Heroes/Knight.controller",
                castClip = "standing melee attack horizontal",
                castClipFallback = "standing melee combo attack ver. 1",
                // WO-285: 3-swing melee combo cycled by the Combo int.
                attackClips = new[] { "standing melee attack horizontal",
                                      "standing melee combo attack ver. 1",
                                      "standing melee combo attack ver. 2" },
                // Per-slot "cast"/special swings (q=Shield Bash strike, w=Bulwark Slam
                // cleave, e=Oath Ward buff pose, r=Lantern Charge cleave ult). The Knight
                // mostly routes through the melee Attack at runtime, but firing Cast with a
                // variant gives each ability slot a distinct swing/pose when the cast path runs.
                spellCastClips = new[] {
                    null,                                   // [0] unused (generic = castClip)
                    "standing melee attack horizontal",     // [1] q  Shield Bash
                    "standing melee attack 360 high",       // [2] w  Bulwark Slam (sweeping)
                    "sword and shield power up",            // [3] e  Oath Ward (buff/ward pose)
                    "standing melee attack downward",       // [4] r  Lantern Charge (heavy)
                },
                searchRoots = KnightRoots },
            new HeroSpec { slug = "Mage",
                controllerPath = "Assets/Resources/Heroes/Mage.controller",
                castClip = "Wizard_Spell_Cast", castClipFallback = "Standing 1H Magic Attack 01",
                attackClips = new[] { "Wizard_Spell_Cast" },   // caster: basic attack = cast
                // Per-spell casts: q Arcane Bolt (1H snap), w Frost Nova (2H area), e Healing
                // Beacon (heal), r Meteor Strike (2H heavy). Each abilities.json slot now plays
                // its own Wizard cast clip.
                spellCastClips = new[] {
                    null,                                   // [0] unused
                    "Standing 1H Magic Attack 01",          // [1] q  Arcane Bolt
                    "Standing 2H Magic Area Attack 01",     // [2] w  Frost Nova
                    "Wizard_Heal",                          // [3] e  Healing Beacon
                    "Standing 2H Magic Attack 03",          // [4] r  Meteor Strike (ult)
                },
                searchRoots = WizardRoots },
            // Ranger now HAS a real aim pose (WO-283); arrows fly via the projectile
            // system, so the aim/idle is the visible "cast" (bow gap is cosmetic-only).
            // Ranger has no distinct per-spell clips in Action/Ranger, so all four slots
            // share the aim pose (spellCastClips omitted → every variant falls back to the
            // generic Cast). Distinct bow draw/loose clips can be dropped in later.
            new HeroSpec { slug = "Ranger",
                controllerPath = "Assets/Resources/Heroes/Ranger.controller",
                castClip = "Ranger_Aim_Idle", castClipFallback = "Shared_Combat_Idle",
                attackClips = new[] { "Ranger_Aim_Idle" },
                searchRoots = RangerRoots },
            // Cleric (caster) shares the Wizard set; Heal is its primary cast.
            new HeroSpec { slug = "Cleric",
                controllerPath = "Assets/Resources/Heroes/Cleric.controller",
                castClip = "Wizard_Heal", castClipFallback = "Wizard_Spell_Cast",
                attackClips = new[] { "Wizard_Heal" },
                // Cleric per-spell casts (caster kit shares the Wizard clips): q smite,
                // w consecrate area, e Heal (its signature), r big channel.
                spellCastClips = new[] {
                    null,                                   // [0] unused
                    "Standing 1H Magic Attack 02",          // [1] q  smite
                    "Standing 2H Magic Area Attack 02",     // [2] w  consecrate (area)
                    "Wizard_Heal",                          // [3] e  Heal (signature)
                    "Standing 2H Cast Spell 01",            // [4] r  channel ult
                },
                searchRoots = WizardRoots },
        };

        [MenuItem("Defenders/Animation/Build Hero Animators (Mixamo)")]
        public static void BuildAll()
        {
            foreach (var spec in Specs) Build(spec);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("[HeroAnimatorFactory] BuildAll complete — Knight / Mage / Ranger / Cleric.");
        }

        private static void Build(HeroSpec spec)
        {
            AnimationClip idle    = LoadClip(IdleClip,    spec.searchRoots);
            AnimationClip walk    = LoadClip(WalkClip,    spec.searchRoots);
            AnimationClip run     = LoadClip(RunClip,     spec.searchRoots);
            AnimationClip victory = LoadClip(VictoryClip, spec.searchRoots);
            AnimationClip hit     = LoadClip(HitClip,   spec.searchRoots);
            AnimationClip death   = LoadClip(DeathClip, spec.searchRoots);
            AnimationClip deathL  = LoadClip(DeathLeftClip,  spec.searchRoots);
            AnimationClip deathR  = LoadClip(DeathRightClip, spec.searchRoots);
            AnimationClip block   = LoadClip(BlockClip, spec.searchRoots);
            AnimationClip cast    = LoadClip(spec.castClip, spec.searchRoots);
            if (cast == null && !string.IsNullOrEmpty(spec.castClipFallback))
            {
                cast = LoadClip(spec.castClipFallback, spec.searchRoots);
                if (cast != null)
                    Debug.LogWarning($"[HeroAnimatorFactory] {spec.slug}: cast clip '{spec.castClip}' " +
                                     $"missing — using fallback '{spec.castClipFallback}' (placeholder).");
            }

            // Idempotent: recreate the controller from scratch.
            AssetDatabase.DeleteAsset(spec.controllerPath);
            var ctrl = AnimatorController.CreateAnimatorControllerAtPath(spec.controllerPath);

            // Canonical AnimParams set (WO-284) — declared on every hero controller so
            // ActorAnimator's guarded verbs all resolve. States exist for the ones with
            // clips; the rest are declared-but-unused (a safe no-op) for future polish.
            ctrl.AddParameter("Speed",    AnimatorControllerParameterType.Float);
            ctrl.AddParameter("InCombat", AnimatorControllerParameterType.Bool);
            ctrl.AddParameter("Attack",   AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("Combo",    AnimatorControllerParameterType.Int);
            ctrl.AddParameter("Cast",     AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("CastVariant", AnimatorControllerParameterType.Int); // which spell (0=generic, q/w/e/r=1..4)
            ctrl.AddParameter("WindUp",   AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("Block",    AnimatorControllerParameterType.Bool);
            ctrl.AddParameter("Hit",      AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("HitDir",   AnimatorControllerParameterType.Int);
            ctrl.AddParameter("Dead",     AnimatorControllerParameterType.Bool);
            ctrl.AddParameter("DeathDir", AnimatorControllerParameterType.Int);
            ctrl.AddParameter("Victory",  AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("Injured",  AnimatorControllerParameterType.Bool); // WO-493 #5 / WO-497: wounded-stance swap

            var sm = ctrl.layers[0].stateMachine;

            // ── Locomotion: a 1-D blend tree on Speed (Idle→Walk→Run) ──────────
            // HeroLocomotion feeds a scalar Speed, so a 1-D forward blend is the
            // right model (strafe clips left for a later 2-D pass).
            var locoState = sm.AddState("Locomotion");
            sm.defaultState = locoState;

            var blend = new BlendTree { name = "Locomotion", blendType = BlendTreeType.Simple1D,
                                        blendParameter = "Speed",
                                        // CRITICAL: Unity defaults useAutomaticThresholds = true, which
                                        // OVERWRITES the AddChild thresholds with auto-spaced 0/0.5/1 —
                                        // that's why walk@6/run@9 never stuck and the hero skipped walk
                                        // (Speed 0..6 vs thresholds 0/0.5/1 = always max = run). Turn it
                                        // OFF so the explicit thresholds below are honored.
                                        useAutomaticThresholds = false };
            AssetDatabase.AddObjectToAsset(blend, ctrl);
            locoState.motion = blend;
            // Null-guarded children: only add the clips that loaded. Always have at
            // least one motion so the state isn't empty.
            // WALK-FEEL FIX (owner ticket 2026-07-02 "animations didn't feel like walking"):
            // HeroLocomotion feeds Speed = Velocity.magnitude with _moveSpeed = 6, so full
            // stick = 6 m/s — a RUN pace. The old tree centred WALK at 6 (Run at an
            // unreachable 9), so the hero always glided at 6 m/s on a walk-cadence clip;
            // on top of that HeroBodySwapper.HeroAnimSpeed halves ALL animator playback
            // (0.5×), halving the stride cadence again → heavy foot-slide. New bands:
            // idle@0 / walk@2 / run@6 — full speed plays the RUN clip. Per-child timeScale
            // compensates the 0.5× global so LOCOMOTION cadence roughly matches distance
            // travelled without touching the tuned cast/attack playback: walk ×2 (net 1.0×,
            // ~Mixamo walk cadence at ~2 m/s) and run ×3 (net 1.5×, ~4.5 m/s visual stride
            // at 6 m/s travel — close enough to read as running, tune here if needed).
            var added = new List<float>();
            if (idle != null) { blend.AddChild(idle, 0f);  added.Add(0f); }
            if (walk != null) { blend.AddChild(walk, 2f);  added.Add(2f); }
            if (run  != null) { blend.AddChild(run,  6f);  added.Add(6f); }
            ApplyLocomotionCadence(blend);
            if (added.Count == 0)
                Debug.LogWarning($"[HeroAnimatorFactory] {spec.slug}: no locomotion clips found — " +
                                 "Locomotion state is empty.");

            // ── WO-493 #5 / WO-497: Injured locomotion swap ────────────────────
            // A SECOND 1-D blend tree on Speed (the wounded idle/limp/stagger),
            // entered when Injured==true and returned when Injured==false — the hero
            // reads "hurt" below ~30% HP (HeroHealth.UpdateInjuredState drives
            // ActorAnimator.SetInjured). Mirrors BuildOrcHumanoidController's swap.
            // Reuses the retargetable Humanoid injured clips from Action/Enemies/;
            // falls back to the healthy locomotion clips so the state is never empty.
            BuildInjuredLocomotion(ctrl, sm, locoState, idle, walk, run, spec);

            // ── Cast — Any → Cast on the trigger, returns to Locomotion ────────
            // WO-217: snappier — state.speed bumped + tighter exit so recovery is
            // quick. The base-layer Cast is KEPT (full-body fallback / clean attack
            // when standing); the WO-218 upper-body layer overlays the same clip so
            // the hero can also swing WHILE moving.
            // WO-218: GATE this full-body Cast on Speed < StandingSpeedMax so it only
            // fires when standing. While MOVING, the base layer stays in Locomotion
            // (legs keep running) and the upper-body layer alone carries the swing —
            // attacks no longer freeze movement.
            // The GENERIC (variant-0) Cast state — fired when Cast is triggered without a
            // matching per-spell variant (e.g. the no-arg PlayCast() from BattleController /
            // PlayerAttackController). Its Any→Cast transition is UNCONDITIONED on CastVariant
            // so it always wins as the default; the per-variant states below add their own
            // CastVariant==N gate so a specific spell overrides this when set.
            if (cast != null)
            {
                var castState = sm.AddState("Cast");
                castState.motion = cast;
                castState.speed  = AttackSpeed;   // WO-217: faster swing
                var toCast = sm.AddAnyStateTransition(castState);
                toCast.hasExitTime = false; toCast.duration = 0.05f;
                toCast.AddCondition(AnimatorConditionMode.If, 0f, "Cast");
                toCast.AddCondition(AnimatorConditionMode.Less, StandingSpeedMax, "Speed"); // WO-218: standing only
                var castBack = castState.AddTransition(locoState);
                castBack.hasExitTime = true;
                castBack.exitTime = CastExitTime;  // WO-217: return earlier
                castBack.duration = CastExitDur;   // WO-217: tighter blend
            }
            else
            {
                Debug.LogWarning($"[HeroAnimatorFactory] {spec.slug}: no cast clip — " +
                                 "Cast trigger will no-op (param still declared).");
            }

            // ── PER-SPELL casts — Any → CastN on Cast + CastVariant==N (q/w/e/r → 1..4) ──
            // Each ability slot plays its OWN cast clip. The transition adds the CastVariant
            // gate ON TOP of the same Cast/standing conditions, so when HeroAbilities fires
            // Cast with CastVariant = slot+1 the matching state wins; absent slots (null clip
            // or no spellCastClips) simply leave the generic Cast to cover them.
            int spellStates = BuildSpellCastStates(sm, locoState, spec);

            // ── Victory — Any → Victory on the trigger, returns to Locomotion ──
            if (victory != null)
            {
                var vicState = sm.AddState("Victory");
                vicState.motion = victory;
                var toVic = sm.AddAnyStateTransition(vicState);
                toVic.hasExitTime = false; toVic.duration = 0.1f;
                toVic.AddCondition(AnimatorConditionMode.If, 0f, "Victory");
                var vicBack = vicState.AddTransition(locoState);
                vicBack.hasExitTime = true; vicBack.exitTime = 0.95f; vicBack.duration = 0.15f;
            }

            // ── WO-285: Attack (melee combo) — Any → AttackN on Attack + Combo==N ──
            // Knight cycles a 3-swing combo (Combo 0/1/2); other classes get a single
            // Attack state. Mirrors the snappy Cast timing (WO-217). Casters mostly
            // route through Cast at runtime, but the state exists so PlayAttack always
            // animates. Returns to Locomotion after the swing.
            int attackStates = BuildAttackStates(ctrl, sm, locoState, spec);

            // ── WO-285: Hit reaction — Any → Hit on the Hit trigger, back to Loco ──
            if (hit != null)
            {
                var hitState = sm.AddState("Hit");
                hitState.motion = hit;
                var toHit = sm.AddAnyStateTransition(hitState);
                toHit.hasExitTime = false; toHit.duration = 0.04f;
                toHit.canTransitionToSelf = false;
                toHit.AddCondition(AnimatorConditionMode.If, 0f, "Hit");
                var hitBack = hitState.AddTransition(locoState);
                hitBack.hasExitTime = true; hitBack.exitTime = 0.7f; hitBack.duration = 0.1f;
            }

            // ── WO-285: Death — Any → Death on Dead==true (latched), Revive clears ─
            // Dead is a BOOL latch (canonical, WO-284): the death clip holds its last
            // frame and never flickers back to idle. Revive() sets Dead=false →
            // Death → Locomotion so a respawned hero animates normally again.
            if (death != null)
            {
                // Centre/fall death (DeathDir 0). When directional clips are present the
                // generic transition stays UNCONDITIONED on DeathDir so it covers dir 0
                // (and any value with no dedicated state); the Left/Right states below add
                // their own DeathDir gate. Revive (Dead=false) returns every death state.
                var deathState = sm.AddState("Death");
                deathState.motion = death;
                var toDeath = sm.AddAnyStateTransition(deathState);
                toDeath.hasExitTime = false; toDeath.duration = 0.06f;
                toDeath.canTransitionToSelf = false;
                toDeath.AddCondition(AnimatorConditionMode.If, 0f, "Dead");
                var deathBack = deathState.AddTransition(locoState);
                deathBack.hasExitTime = false; deathBack.duration = 0.12f;
                deathBack.AddCondition(AnimatorConditionMode.IfNot, 0f, "Dead");

                // Directional deaths (DeathDirection.Left=1 / Right=2) — topple the right way.
                BuildDirectionalDeath(sm, locoState, "DeathLeft",  deathL, 1);
                BuildDirectionalDeath(sm, locoState, "DeathRight", deathR, 2);
            }

            // ── WO-285: Block — Locomotion ⇄ Block on the Block bool ───────────────
            if (block != null)
            {
                var blockState = sm.AddState("Block");
                blockState.motion = block;
                var toBlock = locoState.AddTransition(blockState);
                toBlock.hasExitTime = false; toBlock.duration = 0.1f;
                toBlock.AddCondition(AnimatorConditionMode.If, 0f, "Block");
                var blockBack = blockState.AddTransition(locoState);
                blockBack.hasExitTime = false; blockBack.duration = 0.12f;
                blockBack.AddCondition(AnimatorConditionMode.IfNot, 0f, "Block");
            }

            // ── WO-218: Upper-Body attack layer ────────────────────────────────
            // A second Override layer (weight 1) masked to arms+torso, driven by the
            // SAME "Cast"/"Attack" triggers. Base layer keeps idle/walk/run on the
            // legs; the upper layer overrides the upper body with the attack/cast clip,
            // so the hero can swing while running. Empty default state = no override
            // when not attacking (legs+arms both come from the base layer).
            if (cast != null)
                AddUpperBodyLayer(ctrl, cast, spec);

            EditorUtility.SetDirty(ctrl);
            Debug.Log($"[HeroAnimatorFactory] {spec.slug} built — Locomotion({added.Count} clips)" +
                      $"{(cast != null ? " + Cast(+UpperBody)" : "")}{(spellStates > 0 ? $" + Spells({spellStates})" : "")}" +
                      $"{(attackStates > 0 ? $" + Attack({attackStates})" : "")}" +
                      $"{(hit != null ? " + Hit" : "")}{(death != null ? " + Death" : "")}{(block != null ? " + Block" : "")}" +
                      $"{(victory != null ? " + Victory" : "")} → {spec.controllerPath}");
        }

        /// <summary>
        /// WO-493 #5 / WO-497: builds the hero's Injured locomotion swap — a second 1-D
        /// blend tree on Speed (wounded idle/limp/stagger) entered when Injured==true and
        /// returned when Injured==false. Mirrors BuildOrcHumanoidController's InjuredLocomotion.
        /// The injured idle/walk/run clips come from Action/Enemies/ (retargetable Humanoid);
        /// any missing injured clip falls back to the matching healthy clip so the tree is
        /// never empty (Injured then reads identical to Locomotion — a safe no-op visually).
        /// </summary>
        private static void BuildInjuredLocomotion(AnimatorController ctrl, AnimatorStateMachine sm,
                                                   AnimatorState locoState, AnimationClip healthyIdle,
                                                   AnimationClip healthyWalk, AnimationClip healthyRun,
                                                   HeroSpec spec)
        {
            AnimationClip injIdle = LoadClip(InjuredIdleClip, InjuredRoots) ?? healthyIdle;
            AnimationClip injWalk = LoadClip(InjuredWalkClip, InjuredRoots) ?? healthyWalk;
            AnimationClip injRun  = LoadClip(InjuredRunClip,  InjuredRoots) ?? healthyRun;

            var injuredState = sm.AddState("InjuredLocomotion");
            var injTree = new BlendTree { name = "InjuredLocomotion", blendType = BlendTreeType.Simple1D,
                                          blendParameter = "Speed", useAutomaticThresholds = false };
            AssetDatabase.AddObjectToAsset(injTree, ctrl);
            injuredState.motion = injTree;

            int injChildren = 0;
            // Match the healthy thresholds (idle@0 / walk@2 / run@6, walk-feel fix — see
            // the Locomotion tree above) so the swap reads at the same Speed bands the
            // hero already feeds. Same cadence compensation for the 0.5× global playback.
            if (injIdle != null) { injTree.AddChild(injIdle, 0f); injChildren++; }
            if (injWalk != null) { injTree.AddChild(injWalk, 2f); injChildren++; }
            if (injRun  != null) { injTree.AddChild(injRun,  6f); injChildren++; }
            ApplyLocomotionCadence(injTree);
            if (injChildren == 0)
                Debug.LogWarning($"[HeroAnimatorFactory] {spec.slug}: no injured/healthy locomotion " +
                                 "clips — InjuredLocomotion state is empty.");

            // Locomotion ⇄ InjuredLocomotion on the Injured bool.
            var toInjured = locoState.AddTransition(injuredState);
            toInjured.hasExitTime = false; toInjured.duration = 0.2f;
            toInjured.AddCondition(AnimatorConditionMode.If, 0f, "Injured");
            var fromInjured = injuredState.AddTransition(locoState);
            fromInjured.hasExitTime = false; fromInjured.duration = 0.2f;
            fromInjured.AddCondition(AnimatorConditionMode.IfNot, 0f, "Injured");
        }

        /// <summary>
        /// CLEANUP 2026-07-03: this used to set per-child timeScale (walk ×2 / run ×3) PURELY to
        /// cancel HeroBodySwapper.HeroAnimSpeed's global 0.5× playback (see the old comments). Now
        /// that the global is NATURAL 1.0× (proper AccuRIG/ActorCore mocap), those multipliers would
        /// OVER-speed the locomotion (walk 2×, run 3×). Reset every child to its authored 1.0× so the
        /// mocap plays at its authored cadence. (Was: run @6 → timeScale 3, walk @2 → timeScale 2.)
        /// </summary>
        private static void ApplyLocomotionCadence(BlendTree tree)
        {
            var kids = tree.children;                    // BlendTree.children returns a copy
            for (int i = 0; i < kids.Length; i++)
            {
                kids[i].timeScale = 1f; // natural authored speed — no compensation for a global multiplier
            }
            tree.children = kids;                        // write the modified copy back
        }

        /// <summary>
        /// WO-285: builds the melee Attack state(s). A single clip → one "Attack"
        /// state fired by the Attack trigger. Multiple clips (Knight combo) → one
        /// state per clip ("Attack0/1/2"), each entered when the Attack trigger fires
        /// AND Combo == that index, so PlayerAttackController cycling Combo plays a
        /// different swing each hit. Every state returns to Locomotion (snappy, WO-217).
        /// Returns the number of attack states built (0 = no clips found).
        /// </summary>
        private static int BuildAttackStates(AnimatorController ctrl, AnimatorStateMachine sm,
                                             AnimatorState locoState, HeroSpec spec)
        {
            if (spec.attackClips == null || spec.attackClips.Length == 0) return 0;

            int built = 0;
            bool combo = spec.attackClips.Length > 1;
            for (int i = 0; i < spec.attackClips.Length; i++)
            {
                var clip = LoadClip(spec.attackClips[i], spec.searchRoots);
                if (clip == null) continue;

                var state = sm.AddState(combo ? $"Attack{i}" : "Attack");
                state.motion = clip;
                state.speed  = AttackSpeed;   // WO-217: snappier swing

                var toAttack = sm.AddAnyStateTransition(state);
                toAttack.hasExitTime = false; toAttack.duration = 0.05f;
                toAttack.canTransitionToSelf = false;
                toAttack.AddCondition(AnimatorConditionMode.If, 0f, "Attack");
                // WO-218: full-body melee only when standing — while moving the legs
                // stay in Locomotion and the upper-body layer carries the swing.
                toAttack.AddCondition(AnimatorConditionMode.Less, StandingSpeedMax, "Speed");
                if (combo)
                    toAttack.AddCondition(AnimatorConditionMode.Equals, i, "Combo");

                var back = state.AddTransition(locoState);
                back.hasExitTime = true; back.exitTime = CastExitTime; back.duration = CastExitDur;
                built++;
            }
            return built;
        }

        /// <summary>
        /// PER-SPELL casts: one Cast state per ability slot. For each non-null entry in
        /// spec.spellCastClips[1..4] builds a "Cast_q/w/e/r" state whose Any→state transition
        /// fires on the Cast trigger AND CastVariant == that index. The generic Cast state
        /// (built by the caller, unconditioned on CastVariant) covers variant 0 and any slot
        /// without its own clip. Each state returns to Locomotion with the snappy timing.
        /// Standing-gated like the generic cast (legs keep moving via the upper-body layer).
        /// Returns the number of per-spell states built.
        /// </summary>
        private static int BuildSpellCastStates(AnimatorStateMachine sm, AnimatorState locoState, HeroSpec spec)
        {
            if (spec.spellCastClips == null) return 0;
            string[] slotName = { "0", "q", "w", "e", "r" };
            int built = 0;
            for (int v = 1; v < spec.spellCastClips.Length && v <= 4; v++)
            {
                string basename = spec.spellCastClips[v];
                if (string.IsNullOrEmpty(basename)) continue;
                var clip = LoadClip(basename, spec.searchRoots);
                if (clip == null) continue;

                var state = sm.AddState($"Cast_{slotName[v]}");
                state.motion = clip;
                state.speed  = AttackSpeed;

                var toState = sm.AddAnyStateTransition(state);
                toState.hasExitTime = false; toState.duration = 0.05f;
                toState.canTransitionToSelf = false;
                toState.AddCondition(AnimatorConditionMode.If, 0f, "Cast");
                toState.AddCondition(AnimatorConditionMode.Equals, v, "CastVariant");
                toState.AddCondition(AnimatorConditionMode.Less, StandingSpeedMax, "Speed");

                var back = state.AddTransition(locoState);
                back.hasExitTime = true; back.exitTime = CastExitTime; back.duration = CastExitDur;
                built++;
            }
            return built;
        }

        /// <summary>
        /// Builds one directional Death state ("DeathLeft"/"DeathRight") gated on
        /// Dead==true AND DeathDir==dirValue, returning to Locomotion when Dead clears
        /// (Revive). Null-guarded — a missing clip skips the state and the generic Death
        /// (DeathDir 0, unconditioned) still covers every direction.
        /// </summary>
        private static void BuildDirectionalDeath(AnimatorStateMachine sm, AnimatorState locoState,
                                                  string name, AnimationClip clip, int dirValue)
        {
            if (clip == null) return;
            var state = sm.AddState(name);
            state.motion = clip;
            var to = sm.AddAnyStateTransition(state);
            to.hasExitTime = false; to.duration = 0.06f;
            to.canTransitionToSelf = false;
            to.AddCondition(AnimatorConditionMode.If, 0f, "Dead");
            to.AddCondition(AnimatorConditionMode.Equals, dirValue, "DeathDir");
            var back = state.AddTransition(locoState);
            back.hasExitTime = false; back.duration = 0.12f;
            back.AddCondition(AnimatorConditionMode.IfNot, 0f, "Dead");
        }

        /// <summary>
        /// WO-218: adds an "Upper Body" Override layer (weight 1) masked to arms +
        /// torso so the hero can attack while moving. Layer holds an empty default
        /// state (Empty) and a Cast state with the attack clip; Any→Cast on the same
        /// "Cast" trigger, then back to Empty. While not casting the upper layer sits
        /// on the empty state and contributes nothing (legs+arms = base layer).
        /// Per-spell: also builds an upper-body state per spellCastClips entry, gated
        /// the same way (Cast + CastVariant==N), so a moving caster's arms play the
        /// SPECIFIC spell while the legs keep running.
        /// </summary>
        private static void AddUpperBodyLayer(AnimatorController ctrl, AnimationClip cast, HeroSpec spec)
        {
            var mask = EnsureUpperBodyMask();

            var sm = new AnimatorStateMachine { name = "Upper Body" };
            AssetDatabase.AddObjectToAsset(sm, ctrl);

            // Empty default — no override unless an attack is in progress.
            var empty = sm.AddState("Empty");
            sm.defaultState = empty;

            // Upper-body attack state — same clip, same snappy speed (WO-217).
            var upperCast = sm.AddState("CastUpper");
            upperCast.motion = cast;
            upperCast.speed  = AttackSpeed;

            var toCast = sm.AddAnyStateTransition(upperCast);
            toCast.hasExitTime = false; toCast.duration = 0.05f;
            toCast.canTransitionToSelf = false;
            toCast.AddCondition(AnimatorConditionMode.If, 0f, "Cast");

            // WO-285: the same overlay also fires on the melee Attack trigger, so a
            // Knight swing plays on the upper body while the legs keep walking/running.
            var toAttack = sm.AddAnyStateTransition(upperCast);
            toAttack.hasExitTime = false; toAttack.duration = 0.05f;
            toAttack.canTransitionToSelf = false;
            toAttack.AddCondition(AnimatorConditionMode.If, 0f, "Attack");

            var back = upperCast.AddTransition(empty);
            back.hasExitTime = true;
            back.exitTime = CastExitTime;
            back.duration = CastExitDur;

            // Per-spell upper-body overlays (Cast + CastVariant==N) so a moving caster's
            // arms play the specific spell. Mirrors the base-layer per-spell states.
            if (spec.spellCastClips != null)
            {
                string[] slotName = { "0", "q", "w", "e", "r" };
                for (int v = 1; v < spec.spellCastClips.Length && v <= 4; v++)
                {
                    string basename = spec.spellCastClips[v];
                    if (string.IsNullOrEmpty(basename)) continue;
                    var clip = LoadClip(basename, spec.searchRoots);
                    if (clip == null) continue;

                    var st = sm.AddState($"CastUpper_{slotName[v]}");
                    st.motion = clip;
                    st.speed  = AttackSpeed;

                    var toV = sm.AddAnyStateTransition(st);
                    toV.hasExitTime = false; toV.duration = 0.05f;
                    toV.canTransitionToSelf = false;
                    toV.AddCondition(AnimatorConditionMode.If, 0f, "Cast");
                    toV.AddCondition(AnimatorConditionMode.Equals, v, "CastVariant");

                    var vBack = st.AddTransition(empty);
                    vBack.hasExitTime = true; vBack.exitTime = CastExitTime; vBack.duration = CastExitDur;
                }
            }

            var layer = new AnimatorControllerLayer
            {
                name             = "Upper Body",
                stateMachine     = sm,
                defaultWeight    = 1f,
                blendingMode     = AnimatorLayerBlendingMode.Override,
                avatarMask       = mask,
            };
            ctrl.AddLayer(layer);
        }

        /// <summary>
        /// WO-218: creates (or rebuilds) the arms+torso AvatarMask asset. Enables
        /// every humanoid body part, then DISABLES the legs + root so the upper-body
        /// layer never fights the base layer's locomotion. Idempotent — overwrites
        /// the asset at <see cref="UpperMaskPath"/>.
        /// </summary>
        private static AvatarMask EnsureUpperBodyMask()
        {
            var mask = new AvatarMask();
            // Enable everything first…
            for (int i = 0; i < (int)AvatarMaskBodyPart.LastBodyPart; i++)
                mask.SetHumanoidBodyPartActive((AvatarMaskBodyPart)i, true);
            // …then turn off legs + root so they stay driven by the base (locomotion) layer.
            mask.SetHumanoidBodyPartActive(AvatarMaskBodyPart.Root,      false);
            mask.SetHumanoidBodyPartActive(AvatarMaskBodyPart.LeftLeg,   false);
            mask.SetHumanoidBodyPartActive(AvatarMaskBodyPart.RightLeg,  false);
            mask.SetHumanoidBodyPartActive(AvatarMaskBodyPart.LeftFootIK,  false);
            mask.SetHumanoidBodyPartActive(AvatarMaskBodyPart.RightFootIK, false);

            AssetDatabase.DeleteAsset(UpperMaskPath);
            AssetDatabase.CreateAsset(mask, UpperMaskPath);
            return mask;
        }

        /// <summary>Load the motion AnimationClip from an Assets/Action FBX by basename.
        /// Skips __preview__ AND bind/T-pose clips (iClone8 exports like simple_walk
        /// ship a "0_T-Pose" take alongside the real "…TempMotion" walk — we want the
        /// motion, not the bind pose). Null + warn if absent.</summary>
        private static AnimationClip LoadClip(string fbxBaseName, string[] searchRoots = null)
        {
            // WO-283: search the per-type roots in order (type folder first, then
            // Shared/), falling back to the legacy flat Assets/Action/ for old clips.
            object[] assets = null;
            string path = null;
            var roots = new List<string>();
            if (searchRoots != null) roots.AddRange(searchRoots);
            roots.Add(ActionDir);
            foreach (var root in roots)
            {
                string candidate = root + fbxBaseName + ".fbx";
                var found = AssetDatabase.LoadAllAssetsAtPath(candidate);
                if (found != null && found.Length > 0) { assets = found; path = candidate; break; }
            }
            if (assets == null || assets.Length == 0)
            {
                Debug.LogWarning($"[HeroAnimatorFactory] clip FBX not found: {fbxBaseName} " +
                                 $"(searched {string.Join(", ", roots)})");
                return null;
            }
            AnimationClip fallback = null;
            foreach (var a in assets)
            {
                if (!(a is AnimationClip clip)) continue;
                if (clip.name.StartsWith("__preview__")) continue;
                string n = clip.name.ToLowerInvariant();
                // Skip bind/T-pose takes (iClone8 "0_T-Pose"); keep the first as a
                // fallback in case the FBX has only one usable clip.
                if (n.Contains("t-pose") || n.Contains("tpose") || n.Contains("bind"))
                {
                    fallback ??= clip;
                    continue;
                }
                return clip;   // the real motion take
            }
            if (fallback != null)
                Debug.LogWarning($"[HeroAnimatorFactory] {path}: only a T-pose/bind clip found — using it.");
            else
                Debug.LogWarning($"[HeroAnimatorFactory] no motion AnimationClip inside {path}");
            return fallback;
        }
    }
}
