// =============================================================================
// HeroAnimatorFactory — builds per-class hero AnimatorControllers from the
// Mixamo clips in Assets/Action/ (WO-140). Replaces the obsolete Tripo-era
// HeroAnimatorSetup (which scraped 2 generic NLA takes per FBX).
// -----------------------------------------------------------------------------
// Data-driven: ONE Build(HeroSpec) algorithm consumes a per-class spec, so the
// three heroes are three spec literals (not three code paths) — refactor-ready
// toward a shared AnimatorBuildSpec when the catalog grows (NOT a meta-factory;
// see WO-140). NOT recursive: a controller is a flat state list + a blend tree.
//
// Runtime contract (verified in HeroLocomotion/HeroAbilities, 2026-05-30):
//   Speed   (float)   — HeroLocomotion sets = velocity magnitude → Idle/Walk/Run
//   Cast    (trigger) — HeroAbilities.TryCast → the class attack
//   Victory (trigger) — HeroLocomotion on wave clear → victory pose
// Controllers load via Resources.Load("Heroes/<slug>") where slug ∈
// {Knight, Ranger, Mage}; output paths are fixed at Resources/Heroes/<slug>.controller.
//
// Clips are Humanoid (Assets/Action are animationType 3 + CreateFromThisModel),
// so one clip retargets onto every hero. Every clip lookup is null-guarded — a
// missing FBX logs a warning and skips that state; the build still completes.
// =============================================================================
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

namespace DeNelle.Editor
{
    public static class HeroAnimatorFactory
    {
        // WO-283: clips now live in per-type subfolders under Assets/Action/. Each
        // hero searches its type folder first, then Shared/ (the base set every model
        // retargets). ActionDir kept for the legacy flat-folder fallback.
        private const string ActionDir = "Assets/Action/";
        private const string SharedDir = "Assets/Action/Shared/";

        // ── WO-217 / WO-218 tuning ───────────────────────────────────────────
        // Attack/cast snappiness (WO-217): play the swing faster + recover quick.
        private const float AttackSpeed  = 1.3f;   // cast-state speed multiplier (1.2–1.35)
        private const float CastExitTime = 0.75f;  // return earlier than the old 0.9
        private const float CastExitDur  = 0.06f;  // tighter blend back to locomotion
        // Upper-body attack layer (WO-218): lets the hero swing/cast while moving.
        // Mask generated by EnsureUpperBodyMask(); arms+torso enabled, legs+root off.
        private const string UpperMaskPath = "Assets/Generated/Animators/HeroUpperBody.mask";

        // Shared locomotion clips (all classes) — canonical WO-283 Shared/ basenames.
        private const string IdleClip      = "Shared_Idle";
        private const string WalkClip      = "Shared_Walk_Forward";
        private const string RunClip       = "Shared_Run_Forward";
        private const string VictoryClip   = "Shared_Victory_Pose";

        private struct HeroSpec
        {
            public string slug;            // Knight | Ranger | Mage | Cleric
            public string controllerPath;  // Resources/Heroes/<slug>.controller
            public string castClip;        // per-class attack clip basename
            public string castClipFallback;// used + warned if the primary is absent
            public string[] searchRoots;   // WO-283: type folder first, then Shared/
        }

        // WO-283 §1 type->folder mapping. Casters (Mage + Cleric) share the Wizard set.
        private static readonly string[] KnightRoots = { "Assets/Action/Knight/",  SharedDir };
        private static readonly string[] RangerRoots = { "Assets/Action/Ranger/",  SharedDir };
        private static readonly string[] WizardRoots = { "Assets/Action/Wizard/",  SharedDir };

        private static readonly HeroSpec[] Specs =
        {
            new HeroSpec { slug = "Knight",
                controllerPath = "Assets/Resources/Heroes/Knight.controller",
                castClip = "standing melee attack horizontal",
                castClipFallback = "standing melee combo attack ver. 1",
                searchRoots = KnightRoots },
            new HeroSpec { slug = "Mage",
                controllerPath = "Assets/Resources/Heroes/Mage.controller",
                castClip = "Wizard_Spell_Cast", castClipFallback = "Standing 1H Magic Attack 01",
                searchRoots = WizardRoots },
            // Ranger now HAS a real aim pose (WO-283); arrows fly via the projectile
            // system, so the aim/idle is the visible "cast" (bow gap is cosmetic-only).
            new HeroSpec { slug = "Ranger",
                controllerPath = "Assets/Resources/Heroes/Ranger.controller",
                castClip = "Ranger_Aim_Idle", castClipFallback = "Shared_Combat_Idle",
                searchRoots = RangerRoots },
            // Cleric (caster) shares the Wizard set; Heal is its primary cast.
            new HeroSpec { slug = "Cleric",
                controllerPath = "Assets/Resources/Heroes/Cleric.controller",
                castClip = "Wizard_Heal", castClipFallback = "Wizard_Spell_Cast",
                searchRoots = WizardRoots },
        };

        [MenuItem("Defenders/Animation/Build Hero Animators (Mixamo)")]
        public static void BuildAll()
        {
            foreach (var spec in Specs) Build(spec);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("[HeroAnimatorFactory] BuildAll complete — Knight / Mage / Ranger / Cleric.");
        }

        private static void Build(HeroSpec spec)
        {
            AnimationClip idle    = LoadClip(IdleClip,    spec.searchRoots);
            AnimationClip walk    = LoadClip(WalkClip,    spec.searchRoots);
            AnimationClip run     = LoadClip(RunClip,     spec.searchRoots);
            AnimationClip victory = LoadClip(VictoryClip, spec.searchRoots);
            AnimationClip cast    = LoadClip(spec.castClip, spec.searchRoots);
            if (cast == null && !string.IsNullOrEmpty(spec.castClipFallback))
            {
                cast = LoadClip(spec.castClipFallback, spec.searchRoots);
                if (cast != null)
                    Debug.LogWarning($"[HeroAnimatorFactory] {spec.slug}: cast clip '{spec.castClip}' " +
                                     $"missing — using fallback '{spec.castClipFallback}' (placeholder).");
            }

            // Idempotent: recreate the controller from scratch.
            AssetDatabase.DeleteAsset(spec.controllerPath);
            var ctrl = AnimatorController.CreateAnimatorControllerAtPath(spec.controllerPath);

            ctrl.AddParameter("Speed",   AnimatorControllerParameterType.Float);
            ctrl.AddParameter("Cast",    AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("Victory", AnimatorControllerParameterType.Trigger);

            var sm = ctrl.layers[0].stateMachine;

            // ── Locomotion: a 1-D blend tree on Speed (Idle→Walk→Run) ──────────
            // HeroLocomotion feeds a scalar Speed, so a 1-D forward blend is the
            // right model (strafe clips left for a later 2-D pass).
            var locoState = sm.AddState("Locomotion");
            sm.defaultState = locoState;

            var blend = new BlendTree { name = "Locomotion", blendType = BlendTreeType.Simple1D,
                                        blendParameter = "Speed",
                                        // CRITICAL: Unity defaults useAutomaticThresholds = true, which
                                        // OVERWRITES the AddChild thresholds with auto-spaced 0/0.5/1 —
                                        // that's why walk@6/run@9 never stuck and the hero skipped walk
                                        // (Speed 0..6 vs thresholds 0/0.5/1 = always max = run). Turn it
                                        // OFF so the explicit thresholds below are honored.
                                        useAutomaticThresholds = false };
            AssetDatabase.AddObjectToAsset(blend, ctrl);
            locoState.motion = blend;
            // Null-guarded children: only add the clips that loaded. Always have at
            // least one motion so the state isn't empty.
            // Thresholds tuned to HeroLocomotion's actual feed: _moveSpeed = 6, so
            // Speed (= Velocity.magnitude) ramps 0→6. The hero has ONE move speed,
            // so 6 must land in the WALK band (else it skips walk → straight to run,
            // the "skips walk" bug). Walk centred at 6; Run only if speed exceeds ~9.
            var added = new List<float>();
            if (idle != null) { blend.AddChild(idle, 0f);  added.Add(0f); }
            if (walk != null) { blend.AddChild(walk, 6f);  added.Add(6f); }
            if (run  != null) { blend.AddChild(run,  9f);  added.Add(9f); }
            if (added.Count == 0)
                Debug.LogWarning($"[HeroAnimatorFactory] {spec.slug}: no locomotion clips found — " +
                                 "Locomotion state is empty.");

            // ── Cast — Any → Cast on the trigger, returns to Locomotion ────────
            // WO-217: snappier — state.speed bumped + tighter exit so recovery is
            // quick. The base-layer Cast is KEPT (full-body fallback / clean attack
            // when standing); the WO-218 upper-body layer overlays the same clip so
            // the hero can also swing WHILE moving.
            if (cast != null)
            {
                var castState = sm.AddState("Cast");
                castState.motion = cast;
                castState.speed  = AttackSpeed;   // WO-217: faster swing
                var toCast = sm.AddAnyStateTransition(castState);
                toCast.hasExitTime = false; toCast.duration = 0.05f;
                toCast.AddCondition(AnimatorConditionMode.If, 0f, "Cast");
                var castBack = castState.AddTransition(locoState);
                castBack.hasExitTime = true;
                castBack.exitTime = CastExitTime;  // WO-217: return earlier
                castBack.duration = CastExitDur;   // WO-217: tighter blend
            }
            else
            {
                Debug.LogWarning($"[HeroAnimatorFactory] {spec.slug}: no cast clip — " +
                                 "Cast trigger will no-op (param still declared).");
            }

            // ── Victory — Any → Victory on the trigger, returns to Locomotion ──
            if (victory != null)
            {
                var vicState = sm.AddState("Victory");
                vicState.motion = victory;
                var toVic = sm.AddAnyStateTransition(vicState);
                toVic.hasExitTime = false; toVic.duration = 0.1f;
                toVic.AddCondition(AnimatorConditionMode.If, 0f, "Victory");
                var vicBack = vicState.AddTransition(locoState);
                vicBack.hasExitTime = true; vicBack.exitTime = 0.95f; vicBack.duration = 0.15f;
            }

            // ── WO-218: Upper-Body attack layer ────────────────────────────────
            // A second Override layer (weight 1) masked to arms+torso, driven by the
            // SAME "Cast" trigger. Base layer keeps idle/walk/run on the legs; the
            // upper layer overrides the upper body with the attack/cast clip, so the
            // hero can swing while running. Empty default state = no override when
            // not attacking (legs+arms both come from the base layer).
            if (cast != null)
                AddUpperBodyLayer(ctrl, cast);

            EditorUtility.SetDirty(ctrl);
            Debug.Log($"[HeroAnimatorFactory] {spec.slug} built — Locomotion({added.Count} clips)" +
                      $"{(cast != null ? " + Cast(+UpperBody)" : "")}{(victory != null ? " + Victory" : "")} " +
                      $"→ {spec.controllerPath}");
        }

        /// <summary>
        /// WO-218: adds an "Upper Body" Override layer (weight 1) masked to arms +
        /// torso so the hero can attack while moving. Layer holds an empty default
        /// state (Empty) and a Cast state with the attack clip; Any→Cast on the same
        /// "Cast" trigger, then back to Empty. While not casting the upper layer sits
        /// on the empty state and contributes nothing (legs+arms = base layer).
        /// </summary>
        private static void AddUpperBodyLayer(AnimatorController ctrl, AnimationClip cast)
        {
            var mask = EnsureUpperBodyMask();

            var sm = new AnimatorStateMachine { name = "Upper Body" };
            AssetDatabase.AddObjectToAsset(sm, ctrl);

            // Empty default — no override unless an attack is in progress.
            var empty = sm.AddState("Empty");
            sm.defaultState = empty;

            // Upper-body attack state — same clip, same snappy speed (WO-217).
            var upperCast = sm.AddState("CastUpper");
            upperCast.motion = cast;
            upperCast.speed  = AttackSpeed;

            var toCast = sm.AddAnyStateTransition(upperCast);
            toCast.hasExitTime = false; toCast.duration = 0.05f;
            toCast.canTransitionToSelf = false;
            toCast.AddCondition(AnimatorConditionMode.If, 0f, "Cast");

            var back = upperCast.AddTransition(empty);
            back.hasExitTime = true;
            back.exitTime = CastExitTime;
            back.duration = CastExitDur;

            var layer = new AnimatorControllerLayer
            {
                name             = "Upper Body",
                stateMachine     = sm,
                defaultWeight    = 1f,
                blendingMode     = AnimatorLayerBlendingMode.Override,
                avatarMask       = mask,
            };
            ctrl.AddLayer(layer);
        }

        /// <summary>
        /// WO-218: creates (or rebuilds) the arms+torso AvatarMask asset. Enables
        /// every humanoid body part, then DISABLES the legs + root so the upper-body
        /// layer never fights the base layer's locomotion. Idempotent — overwrites
        /// the asset at <see cref="UpperMaskPath"/>.
        /// </summary>
        private static AvatarMask EnsureUpperBodyMask()
        {
            var mask = new AvatarMask();
            // Enable everything first…
            for (int i = 0; i < (int)AvatarMaskBodyPart.LastBodyPart; i++)
                mask.SetHumanoidBodyPartActive((AvatarMaskBodyPart)i, true);
            // …then turn off legs + root so they stay driven by the base (locomotion) layer.
            mask.SetHumanoidBodyPartActive(AvatarMaskBodyPart.Root,      false);
            mask.SetHumanoidBodyPartActive(AvatarMaskBodyPart.LeftLeg,   false);
            mask.SetHumanoidBodyPartActive(AvatarMaskBodyPart.RightLeg,  false);
            mask.SetHumanoidBodyPartActive(AvatarMaskBodyPart.LeftFootIK,  false);
            mask.SetHumanoidBodyPartActive(AvatarMaskBodyPart.RightFootIK, false);

            AssetDatabase.DeleteAsset(UpperMaskPath);
            AssetDatabase.CreateAsset(mask, UpperMaskPath);
            return mask;
        }

        /// <summary>Load the motion AnimationClip from an Assets/Action FBX by basename.
        /// Skips __preview__ AND bind/T-pose clips (iClone8 exports like simple_walk
        /// ship a "0_T-Pose" take alongside the real "…TempMotion" walk — we want the
        /// motion, not the bind pose). Null + warn if absent.</summary>
        private static AnimationClip LoadClip(string fbxBaseName, string[] searchRoots = null)
        {
            // WO-283: search the per-type roots in order (type folder first, then
            // Shared/), falling back to the legacy flat Assets/Action/ for old clips.
            object[] assets = null;
            string path = null;
            var roots = new List<string>();
            if (searchRoots != null) roots.AddRange(searchRoots);
            roots.Add(ActionDir);
            foreach (var root in roots)
            {
                string candidate = root + fbxBaseName + ".fbx";
                var found = AssetDatabase.LoadAllAssetsAtPath(candidate);
                if (found != null && found.Length > 0) { assets = found; path = candidate; break; }
            }
            if (assets == null || assets.Length == 0)
            {
                Debug.LogWarning($"[HeroAnimatorFactory] clip FBX not found: {fbxBaseName} " +
                                 $"(searched {string.Join(", ", roots)})");
                return null;
            }
            AnimationClip fallback = null;
            foreach (var a in assets)
            {
                if (!(a is AnimationClip clip)) continue;
                if (clip.name.StartsWith("__preview__")) continue;
                string n = clip.name.ToLowerInvariant();
                // Skip bind/T-pose takes (iClone8 "0_T-Pose"); keep the first as a
                // fallback in case the FBX has only one usable clip.
                if (n.Contains("t-pose") || n.Contains("tpose") || n.Contains("bind"))
                {
                    fallback ??= clip;
                    continue;
                }
                return clip;   // the real motion take
            }
            if (fallback != null)
                Debug.LogWarning($"[HeroAnimatorFactory] {path}: only a T-pose/bind clip found — using it.");
            else
                Debug.LogWarning($"[HeroAnimatorFactory] no motion AnimationClip inside {path}");
            return fallback;
        }
    }
}
