#if UNITY_EDITOR
using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using Newtonsoft.Json.Linq;
using UnityEditor;
using UnityEngine;

namespace DeNelle.Editor
{
    /// <summary>WO-1170 site 3: generates the stake-reward fallback from canonical JSON bytes.</summary>
    public static class StakeRewardsFallbackGenerator
    {
        private const string ResourcesCopy = "Assets/Resources/Data/Canonical/stake-rewards.json";
        private const string StreamingCopy = "Assets/StreamingAssets/Data/Canonical/stake-rewards.json";
        private const string OutputPath = "Assets/_Modules/Core/Platform/Generated/StakeRewardsFallbackData.g.cs";
        private const string MarkerOk = "STAKE_REWARDS_FALLBACK_GEN_OK";
        private const string MarkerFail = "STAKE_REWARDS_FALLBACK_GEN_FAIL";
        private const string Command =
            "powershell -NoProfile -File .\\run-unity-method.ps1 -Method DeNelle.Editor.StakeRewardsFallbackGenerator.Generate -LogName stake-rewards-fallback-gen.log -ExpectMarker STAKE_REWARDS_FALLBACK_GEN_OK";

        [MenuItem("Defenders/Catalog/Regenerate Stake Rewards Fallback (WO-1170)")]
        public static void Generate()
        {
            try
            {
                string root = Directory.GetCurrentDirectory();
                byte[] resources = ReadRequired(root, ResourcesCopy);
                byte[] streaming = ReadRequired(root, StreamingCopy);
                string resourceHash = Sha256(resources);
                string streamingHash = Sha256(streaming);
                if (resourceHash != streamingHash)
                    throw new InvalidOperationException("canonical copies differ: Resources=" +
                        resourceHash + " StreamingAssets=" + streamingHash);

                string json = new UTF8Encoding(false, true).GetString(resources);
                var parsed = JObject.Parse(json);
                var tiers = parsed["tiers"] as JArray;
                if (tiers == null || tiers.Count == 0)
                    throw new InvalidOperationException("canonical table has no tier rows");

                string source = BuildSource(Convert.ToBase64String(resources), resourceHash, resources.Length);
                string output = Path.Combine(root, OutputPath.Replace('/', Path.DirectorySeparatorChar));
                Directory.CreateDirectory(Path.GetDirectoryName(output));
                File.WriteAllBytes(output, new UTF8Encoding(false).GetBytes(source));
                AssetDatabase.ImportAsset(OutputPath, ImportAssetOptions.ForceUpdate);
                Debug.Log($"{MarkerOk} rows={tiers.Count} bytes={resources.Length} sha256={resourceHash} output={OutputPath}");
            }
            catch (Exception ex)
            {
                Debug.LogError($"{MarkerFail} {ex.GetType().Name}: {ex.Message}");
            }
        }

        private static byte[] ReadRequired(string root, string relative)
        {
            string path = Path.Combine(root, relative.Replace('/', Path.DirectorySeparatorChar));
            if (!File.Exists(path)) throw new FileNotFoundException("missing canonical copy", relative);
            return File.ReadAllBytes(path);
        }

        private static string Sha256(byte[] bytes)
        {
            using (var sha = SHA256.Create())
            {
                var result = sha.ComputeHash(bytes);
                var text = new StringBuilder(result.Length * 2);
                foreach (byte value in result) text.Append(value.ToString("x2"));
                return text.ToString();
            }
        }

        private static string BuildSource(string base64, string hash, int byteLength)
        {
            return "// <auto-generated>\n" +
                "// Generated from stake-rewards.json. Do not edit; run StakeRewardsFallbackGenerator.\n" +
                "// WO-1170 site 3: exact canonical bytes replace the hand-maintained reward table.\n" +
                "// </auto-generated>\n\n" +
                "using System;\nusing System.Text;\n\n" +
                "namespace DeNelle.Core.Platform\n{\n" +
                "    public static class StakeRewardsFallbackData\n    {\n" +
                "        public const string SourcePath = \"" + ResourcesCopy + "\";\n" +
                "        public const string SourceSha256 = \"" + hash + "\";\n" +
                "        public const int SourceByteLength = " + byteLength + ";\n" +
                "        public const string RegenerateCommand =\n" +
                "            \"" + Escape(Command) + "\";\n\n" +
                "        private const string Base64 =\n            \"" + base64 + "\";\n\n" +
                "        public static string Json => Encoding.UTF8.GetString(Convert.FromBase64String(Base64));\n" +
                "    }\n}\n";
        }

        private static string Escape(string text) => text.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
#endif
