// =============================================================================
// StructureAddressablesMigrator — move catalog-referenced structure art out of
// Resources, mark it Addressable, and record every move in a GENERATED manifest.
// -----------------------------------------------------------------------------
// OWNER DESIGN (2026-08-17):
//   "all we do is tag a file with what we moved as a json so we store its path"
//   "then we track its dependency with step in step out"
//   "we know where its coming from we do it"
//
// WHY A MANIFEST AND NOT HARDCODED PATHS: ~14 editor scripts hardcode
// "Assets/Resources/Structures". Moving the art breaks every one of them. One
// generated manifest replaces all of those strings with a lookup, makes the move
// REVERSIBLE, and makes it AUDITABLE — you can diff what moved.
//
// ⛔ THE MANIFEST IS GENERATED BY THIS TOOL AND VERIFIED BY A GATE. It is NEVER
// hand-maintained. A hand-kept path list is a second source of truth, and this
// project was bitten FOUR TIMES IN ONE DAY by exactly that class: the
// .tripo-extracted marker that outlived its FBX, the -90 pet forward-yaw
// constant, a stale WO number, and the WizardTower_1 art path. Each was true when
// written and outlived the thing it described. A stale move-manifest is that bug
// with a bigger blast radius — every building in the game.
//
// ⛔ THE MOVE LIST IS THE DEPENDENCY CLOSURE OF THE CATALOG, NOT A FILE-TYPE
// SWEEP. Unity includes the dependencies of anything under Resources/ WHEREVER
// THEY LIVE. So moving the .fbx while leaving its .mat behind relocates 43 MB and
// drags the 19 MB of textures straight back in — the APK barely moves while every
// check reports success. Closure, computed by AssetDatabase, is the only correct
// list. That is also why this tool refuses to move a partial closure.
//
// SAFETY: AssetDatabase.MoveAsset PRESERVES GUIDs, so prefab/material/scene
// references survive the move intact. What does NOT survive is a hardcoded STRING
// path — hence the manifest.
//
// RUN DRY FIRST:
//   -executeMethod DeNelle.Editor.StructureAddressablesMigrator.DryRun
//   -executeMethod DeNelle.Editor.StructureAddressablesMigrator.Run
// =============================================================================

using System.Collections.Generic;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace DeNelle.Editor
{
    /// <summary>Catalog-driven Resources -> Addressables migrator for structure art.</summary>
    public static class StructureAddressablesMigrator
    {
        private const string ResourcesRoot = "Assets/Resources/Structures";
        private const string ArtRoot       = "Assets/Art/Structures";
        // ⛔ NOT UNDER Resources/. The first version wrote this to Resources/Data/Canonical and the
        // data-web regression caught it immediately: anything under Resources is FORCE-INCLUDED, so
        // a tool whose whole purpose is getting bytes OUT of Resources was adding a file TO it — and
        // Resources-only catalogs also beat their StreamingAssets counterpart at runtime, which is
        // the drift that gate exists to prevent. This manifest is EDITOR-ONLY data: the runtime
        // resolves by ADDRESS, never by path, so nothing at runtime needs it.
        private const string ManifestPath  = "Assets/AddressableAssetsData/asset-move-manifest.json";
        private const string CatalogPath   = "Assets/Resources/Data/Canonical/structures-catalog.json";

        private const string OkMarker   = "STRUCTURE_MIGRATE_OK";
        private const string DryMarker  = "STRUCTURE_MIGRATE_DRYRUN_OK";

        [MenuItem("Defenders/Art/Structures -> Addressables (DRY RUN)")]
        public static void DryRunMenu() => DryRun();

        public static void DryRun()  => Execute(dryRun: true);
        public static void Run()     => Execute(dryRun: false);

        // ---------------------------------------------------------------------

        private static void Execute(bool dryRun)
        {
            string mode = dryRun ? "DRY RUN" : "LIVE";
            Debug.Log($"[Migrate] ===== {mode} =====");

            // 1) The move list starts from what the CATALOG actually references. Anything the
            //    catalog does not name is not runtime art and is none of this tool's business.
            var keys = ReadCatalogArtKeys();
            if (keys.Count == 0)
            {
                Debug.LogError("[Migrate] catalog produced ZERO art keys — refusing to move anything. " +
                               "A migration that cannot see its inputs must not guess at them.");
                return;
            }
            Debug.Log($"[Migrate] catalog references {keys.Count} art key(s).");

            // 2) Resolve each key to an asset path, then take the FULL DEPENDENCY CLOSURE.
            var roots = new Dictionary<string, string>();   // key -> asset path
            var missing = new List<string>();
            foreach (var key in keys)
            {
                string path = ResolveResourcesKey(key);
                if (string.IsNullOrEmpty(path)) { missing.Add(key); continue; }
                roots[key] = path;
            }

            if (missing.Count > 0)
            {
                // Not fatal: some catalog keys legitimately point at pack prefabs that are absent on
                // a fresh clone (CLAUDE.md §4 — LogWarning, never throw). But say so loudly, because
                // a key that cannot be resolved also cannot be migrated, and would then be the ONE
                // building that still loads from Resources after the move.
                Debug.LogWarning($"[Migrate] {missing.Count} catalog key(s) do not resolve to an asset and " +
                                 $"will NOT be migrated: {string.Join(", ", missing)}");
            }

            var closure = new SortedSet<string>(System.StringComparer.OrdinalIgnoreCase);
            foreach (var kv in roots)
            {
                closure.Add(kv.Value);
                foreach (var dep in AssetDatabase.GetDependencies(kv.Value, recursive: true))
                {
                    // Only things currently UNDER Resources are a payload problem. A dependency that
                    // already lives outside Resources is fine where it is — moving it would be churn
                    // with no size benefit and extra reference risk.
                    if (dep.StartsWith(ResourcesRoot, System.StringComparison.OrdinalIgnoreCase))
                        closure.Add(dep);
                }
            }

            // 3) What stays behind, and WHY it matters: anything left under Resources that still
            //    references a moved asset would drag it back into the payload. Report the overlap so
            //    a partial move is visible instead of silently defeating the migration.
            var stayed = System.IO.Directory
                .GetFiles(ResourcesRoot, "*", System.IO.SearchOption.AllDirectories)
                .Select(p => p.Replace('\\', '/'))
                .Where(p => !p.EndsWith(".meta") && !closure.Contains(p))
                .ToList();

            var leakers = new List<string>();
            foreach (var s in stayed)
            {
                foreach (var dep in AssetDatabase.GetDependencies(s, recursive: true))
                {
                    if (dep != s && closure.Contains(dep)) { leakers.Add($"{s} -> {dep}"); break; }
                }
            }

            Debug.Log($"[Migrate] closure = {closure.Count} asset(s) to move; {stayed.Count} file(s) stay.");
            if (leakers.Count > 0)
            {
                Debug.LogError($"[Migrate] ⛔ {leakers.Count} asset(s) STAYING in Resources still reference a " +
                               "MOVED asset. Unity pulls dependencies of Resources assets back into the payload " +
                               "WHEREVER THEY LIVE, so these would silently undo the migration while every gate " +
                               "stays green. Fix the closure before running LIVE:");
                foreach (var l in leakers.Take(15)) Debug.LogError($"[Migrate]     {l}");
                if (!dryRun)
                {
                    Debug.LogError("[Migrate] ABORTED — refusing to perform a move that is already known to leak.");
                    return;
                }
            }

            long bytes = closure.Sum(p => SafeLen(p));
            Debug.Log($"[Migrate] closure size = {bytes / 1048576.0:F1} MB (this is what leaves the Resources payload).");

            // 4) Build the manifest. In DRY RUN it is written but nothing moves, so the exact plan
            //    can be reviewed as data before any file is touched.
            var entries = new List<MoveEntry>();
            foreach (var src in closure)
            {
                string rel  = src.Substring(ResourcesRoot.Length).TrimStart('/');
                string dst  = $"{ArtRoot}/{rel}";
                string addr = "Structures/" + System.IO.Path.ChangeExtension(rel, null).Replace('\\', '/');
                entries.Add(new MoveEntry
                {
                    address     = addr,
                    resourcesKey= roots.FirstOrDefault(kv => kv.Value == src).Key,
                    from        = src,
                    to          = dst,
                    guid        = AssetDatabase.AssetPathToGUID(src),
                    bytes       = SafeLen(src),
                });
            }

            WriteManifest(entries, dryRun, bytes);

            if (dryRun)
            {
                Debug.Log($"[Migrate] DRY RUN complete — NOTHING MOVED. Manifest written to {ManifestPath} for review.");
                Debug.Log($"{DryMarker} {entries.Count} planned, {bytes / 1048576.0:F1} MB, {leakers.Count} leak(s)");
                return;
            }

            Debug.LogError("[Migrate] LIVE move is not enabled in this build of the tool — DryRun only. " +
                           "Review the manifest, then implement Run() once the plan is accepted.");
        }

        // ---------------------------------------------------------------------

        private static long SafeLen(string assetPath)
        {
            try { return new System.IO.FileInfo(assetPath).Length; } catch { return 0; }
        }

        /// <summary>Resolve a Resources key ("Structures/Forge") to its asset path, any extension.</summary>
        private static string ResolveResourcesKey(string key)
        {
            string stem = $"{ResourcesRoot}/{key.Substring("Structures/".Length)}";
            foreach (var ext in new[] { ".prefab", ".fbx", ".png", ".jpg", ".jpeg", ".asset", ".mat" })
            {
                string p = stem + ext;
                if (System.IO.File.Exists(p)) return p;
            }
            return null;
        }

        private static List<string> ReadCatalogArtKeys()
        {
            var keys = new SortedSet<string>(System.StringComparer.OrdinalIgnoreCase);
            if (!System.IO.File.Exists(CatalogPath)) return keys.ToList();

            string json = System.IO.File.ReadAllText(CatalogPath);
            foreach (System.Text.RegularExpressions.Match m in
                     System.Text.RegularExpressions.Regex.Matches(json, "\"(Structures/[^\"]+)\""))
            {
                keys.Add(m.Groups[1].Value);
            }
            return keys.ToList();
        }

        private static void WriteManifest(List<MoveEntry> entries, bool dryRun, long bytes)
        {
            var sb = new System.Text.StringBuilder();
            sb.AppendLine("{");
            sb.AppendLine("  \"_generated\": \"DeNelle.Editor.StructureAddressablesMigrator — DO NOT HAND-EDIT.\",");
            sb.AppendLine("  \"_why\": \"Records every asset relocated out of Resources: its old Resources key, old and new paths, GUID and Addressable address. Editor scripts read THIS instead of hardcoding a Resources path, so a future move is one regeneration rather than ~14 edits. A gate asserts every entry still resolves — a stale manifest must FAIL loudly, never render nothing in game.\",");
            sb.AppendLine($"  \"_mode\": \"{(dryRun ? "DRY_RUN — nothing was moved" : "LIVE")}\",");
            sb.AppendLine($"  \"_totalBytes\": {bytes},");
            sb.AppendLine($"  \"_count\": {entries.Count},");
            sb.AppendLine("  \"moves\": [");
            for (int i = 0; i < entries.Count; i++)
            {
                var e = entries[i];
                sb.Append("    { ");
                sb.Append($"\"address\": \"{e.address}\", ");
                sb.Append($"\"resourcesKey\": \"{e.resourcesKey}\", ");
                sb.Append($"\"from\": \"{e.from}\", ");
                sb.Append($"\"to\": \"{e.to}\", ");
                sb.Append($"\"guid\": \"{e.guid}\", ");
                sb.Append($"\"bytes\": {e.bytes}");
                sb.AppendLine(i < entries.Count - 1 ? " }," : " }");
            }
            sb.AppendLine("  ]");
            sb.AppendLine("}");

            System.IO.File.WriteAllText(ManifestPath, sb.ToString());
            AssetDatabase.Refresh();
            Debug.Log($"[Migrate] manifest written: {ManifestPath} ({entries.Count} entries)");
        }

        private struct MoveEntry
        {
            public string address;
            public string resourcesKey;
            public string from;
            public string to;
            public string guid;
            public long   bytes;
        }
    }
}
