// =============================================================================
// StructureAddressablesMigrator — move catalog-referenced structure art out of
// Resources, mark it Addressable, and record every move in a GENERATED manifest.
// -----------------------------------------------------------------------------
// OWNER DESIGN (2026-08-17):
//   "all we do is tag a file with what we moved as a json so we store its path"
//   "then we track its dependency with step in step out"
//   "we know where its coming from we do it"
//
// WHY A MANIFEST AND NOT HARDCODED PATHS: ~14 editor scripts hardcode
// "Assets/Resources/Structures". Moving the art breaks every one of them. One
// generated manifest replaces all of those strings with a lookup, makes the move
// REVERSIBLE, and makes it AUDITABLE — you can diff what moved.
//
// ⛔ THE MANIFEST IS GENERATED BY THIS TOOL AND VERIFIED BY A GATE. It is NEVER
// hand-maintained. A hand-kept path list is a second source of truth, and this
// project was bitten FOUR TIMES IN ONE DAY by exactly that class: the
// .tripo-extracted marker that outlived its FBX, the -90 pet forward-yaw
// constant, a stale WO number, and the WizardTower_1 art path. Each was true when
// written and outlived the thing it described. A stale move-manifest is that bug
// with a bigger blast radius — every building in the game.
//
// ⛔ THE MOVE LIST IS THE DEPENDENCY CLOSURE OF THE CATALOG, NOT A FILE-TYPE
// SWEEP. Unity includes the dependencies of anything under Resources/ WHEREVER
// THEY LIVE. So moving the .fbx while leaving its .mat behind relocates 43 MB and
// drags the 19 MB of textures straight back in — the APK barely moves while every
// check reports success. Closure, computed by AssetDatabase, is the only correct
// list. That is also why this tool refuses to move a partial closure.
//
// SAFETY: AssetDatabase.MoveAsset PRESERVES GUIDs, so prefab/material/scene
// references survive the move intact. What does NOT survive is a hardcoded STRING
// path — hence the manifest.
//
// RUN DRY FIRST:
//   -executeMethod DeNelle.Editor.StructureAddressablesMigrator.DryRun
//   -executeMethod DeNelle.Editor.StructureAddressablesMigrator.Run
// =============================================================================

using System.Collections.Generic;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace DeNelle.Editor
{
    /// <summary>Catalog-driven Resources -> Addressables migrator for structure art.</summary>
    public static class StructureAddressablesMigrator
    {
        private const string ResourcesRoot = DeNelle.Core.AssetRoots.StructureContentLegacyResources;
        // ⛔ A DEDICATED TOP-LEVEL FOLDER, NOT Assets/Art/Structures.
        // The first attempt targeted Assets/Art/Structures, and during its revert a cleanup step
        // resolved 'Assets/Art' instead of 'Assets/Art/Structures' and recursively deleted the
        // ENTIRE Assets/Art tree — 227 tracked files including the CraftPix source art. It was
        // recoverable only because those files were tracked; the same slip one folder over, in
        // Resources/Structures where 226 of 244 files are gitignored, would have destroyed
        // owner-purchased art permanently. A destination that shares no parent with existing art
        // makes that class of mistake impossible rather than merely unlikely.
        private const string ArtRoot       = DeNelle.Core.AssetRoots.StructureContent;
        // ⛔ NOT UNDER Resources/. The first version wrote this to Resources/Data/Canonical and the
        // data-web regression caught it immediately: anything under Resources is FORCE-INCLUDED, so
        // a tool whose whole purpose is getting bytes OUT of Resources was adding a file TO it — and
        // Resources-only catalogs also beat their StreamingAssets counterpart at runtime, which is
        // the drift that gate exists to prevent. This manifest is EDITOR-ONLY data: the runtime
        // resolves by ADDRESS, never by path, so nothing at runtime needs it.
        private const string ManifestPath  = "Assets/AddressableAssetsData/asset-move-manifest.json";
        private const string CatalogPath   = "Assets/Resources/Data/Canonical/structures-catalog.json";

        private const string GroupName  = "Structure_Art";
        private const string OkMarker   = "STRUCTURE_MIGRATE_OK";
        private const string DryMarker  = "STRUCTURE_MIGRATE_DRYRUN_OK";

        [MenuItem("Defenders/Art/Structures -> Addressables (DRY RUN)")]
        public static void DryRunMenu() => DryRun();

        /// <summary>
        /// Moves the WHOLE Resources/Structures folder out of Resources in ONE AssetDatabase
        /// operation, then marks the catalog-referenced art Addressable.
        /// <para>
        /// ⛔ THIS REPLACES THE PER-FILE STRATEGY, WHICH FAILED BADLY. Per-file moves cannot work
        /// here: AssetDatabase.MoveAsset refuses to move a file OUT of a "&lt;name&gt;.fbm" folder AND
        /// refuses to move the .fbm folder itself, because Unity treats .fbm as owned by its FBX.
        /// Routing around that with filesystem moves nested folders into themselves, tripped Unity's
        /// collision auto-rename, and left the tree with 100 regression failures.
        /// </para>
        /// <para>
        /// Moving the PARENT folder sidesteps the whole problem: .fbm folders travel inside it as
        /// ordinary content, Unity handles the reparenting itself, GUIDs are preserved, and it is a
        /// SINGLE operation that either succeeds or fails — no partial state. The cost is that the
        /// ~14 editor scripts hardcoding "Assets/Resources/Structures" must be repointed, which is
        /// exactly what the manifest was built to make mechanical.
        /// </para>
        /// ⚠ Everything under the folder leaves Resources, INCLUDING the small Polyperfect prefab
        /// mirrors the scene builders load. That is fine — they are loaded by editor tooling via
        /// AssetDatabase paths, not Resources.Load, so they follow the manifest like everything else.
        /// </summary>
        [MenuItem("Defenders/Art/Structures -> Addressables (MOVE FOLDER)")]
        public static void MoveFolder()
        {
            if (!AssetDatabase.IsValidFolder(ResourcesRoot))
            {
                Debug.LogError($"[Migrate] '{ResourcesRoot}' not found — already moved, or wrong project.");
                return;
            }

            var settings = UnityEditor.AddressableAssets.AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null)
            {
                Debug.LogError("[Migrate] Addressables settings missing — ABORTED before touching anything. " +
                               "Moving art out of Resources with no Addressables home makes every asset unloadable.");
                return;
            }

            // Count first so the move can be PROVEN rather than assumed.
            int before = System.IO.Directory.GetFiles(ResourcesRoot, "*", System.IO.SearchOption.AllDirectories)
                                            .Count(p => !p.EndsWith(".meta"));

            string err = AssetDatabase.MoveAsset(ResourcesRoot, ArtRoot);
            if (!string.IsNullOrEmpty(err))
            {
                Debug.LogError($"[Migrate] FOLDER MOVE FAILED '{ResourcesRoot}' -> '{ArtRoot}': {err}. " +
                               "Nothing was moved — MoveAsset on a folder is all-or-nothing.");
                return;
            }
            AssetDatabase.Refresh();

            int after = System.IO.Directory.GetFiles(ArtRoot, "*", System.IO.SearchOption.AllDirectories)
                                           .Count(p => !p.EndsWith(".meta"));
            Debug.Log($"[Migrate] folder moved: {before} file(s) before -> {after} at the new root.");
            if (before != after)
            {
                Debug.LogError($"[Migrate] FILE COUNT CHANGED ({before} -> {after}) — files were lost or duplicated " +
                               "in the move. Investigate before building.");
            }

            // Mark ONLY what the catalog references. The rest rides along out of Resources (which is
            // the size win) without needing an address it would never be loaded by.
            var group = settings.FindGroup(GroupName) ?? settings.CreateGroup(
                GroupName, setAsDefaultGroup: false, readOnly: false, postEvent: false,
                schemasToCopy: null,
                types: new[] { typeof(UnityEditor.AddressableAssets.Settings.GroupSchemas.BundledAssetGroupSchema),
                               typeof(UnityEditor.AddressableAssets.Settings.GroupSchemas.ContentUpdateGroupSchema) });

            int marked = 0;
            foreach (var key in ReadCatalogArtKeys())
            {
                string rel = key.Substring("Structures/".Length);
                string path = null;
                foreach (var ext in new[] { ".prefab", ".fbx", ".png", ".jpg", ".jpeg", ".asset", ".mat", ".JPEG" })
                    if (System.IO.File.Exists($"{ArtRoot}/{rel}{ext}")) { path = $"{ArtRoot}/{rel}{ext}"; break; }
                if (path == null) continue;

                string guid = AssetDatabase.AssetPathToGUID(path);
                if (string.IsNullOrEmpty(guid)) continue;
                var entry = settings.CreateOrMoveEntry(guid, group, readOnly: false, postEvent: false);
                if (entry == null) continue;
                entry.SetAddress(key, postEvent: false);   // address == the catalog's own key, verbatim
                marked++;
            }

            settings.SetDirty(UnityEditor.AddressableAssets.Settings.AddressableAssetSettings
                                  .ModificationEvent.BatchModification, null, true, true);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            // Record the move as ONE entry, because that is what actually happened. The per-file
            // manifest belonged to the abandoned per-file strategy; leaving it in place would have
            // described a migration that was never performed, which is precisely the stale-manifest
            // failure the gate exists to catch — and it duly caught it, with 114 false entries.
            WriteFolderManifest(before, after, marked);

            Debug.Log($"[Migrate] marked {marked} catalog asset(s) addressable in '{GroupName}'.");
            Debug.Log($"STRUCTURE_FOLDER_MOVE_OK {after} files, {marked} addressable");
        }

        /// <summary>
        /// Moves any orphaned "&lt;name&gt;.fbm" folder whose FBX has already been migrated, so the
        /// textures follow the model that owns them.
        /// <para>
        /// ⛔ THIS EXISTS BECAUSE THE FIRST LIVE RUN STRANDED THEM. AssetDatabase.MoveAsset refuses
        /// to move a file OUT of a .fbm (the folder belongs to its FBX), so 66 per-file moves failed
        /// while the 20 FBXs succeeded — models in one folder, their textures in another. Moving the
        /// FOLDER is allowed; moving its contents is not. Idempotent and safe to re-run.
        /// </para>
        /// </summary>
        [MenuItem("Defenders/Art/Repair stranded .fbm folders")]
        public static void RepairFbmFolders()
        {
            if (!AssetDatabase.IsValidFolder(ArtRoot))
            {
                Debug.Log("[Migrate] no migrated art root — nothing to repair.");
                Debug.Log("STRUCTURE_FBM_REPAIR_OK 0 moved");
                return;
            }

            int moved = 0, failed = 0, skipped = 0;
            foreach (var dir in System.IO.Directory.GetDirectories(ResourcesRoot, "*.fbm"))
            {
                string src  = dir.Replace('\\', '/');
                string name = System.IO.Path.GetFileName(src);                       // "Forge.fbm"
                string stem = System.IO.Path.GetFileNameWithoutExtension(name);      // "Forge"

                // Only follow an FBX that has ACTUALLY moved. A .fbm whose model is still in
                // Resources must stay put — moving it would strand the textures the other way.
                if (!System.IO.File.Exists($"{ArtRoot}/{stem}.fbx")) { skipped++; continue; }

                string dst = $"{ArtRoot}/{name}";
                string err = AssetDatabase.MoveAsset(src, dst);
                if (!string.IsNullOrEmpty(err))
                {
                    failed++;
                    Debug.LogError($"[Migrate] .fbm repair FAILED '{src}' -> '{dst}': {err}");
                }
                else
                {
                    moved++;
                    Debug.Log($"[Migrate] .fbm moved with its model: {name}");
                }
            }

            AssetDatabase.Refresh();
            Debug.Log($"[Migrate] .fbm repair: {moved} moved, {skipped} left (model still in Resources), {failed} failed.");
            Debug.Log(failed == 0 ? $"STRUCTURE_FBM_REPAIR_OK {moved} moved"
                                  : $"STRUCTURE_FBM_REPAIR_FAIL {failed}");
        }

        public static void DryRun()  => Execute(dryRun: true);
        public static void Run()     => Execute(dryRun: false);

        // ---------------------------------------------------------------------

        private static void Execute(bool dryRun)
        {
            string mode = dryRun ? "DRY RUN" : "LIVE";
            Debug.Log($"[Migrate] ===== {mode} =====");

            // 1) The move list starts from what the CATALOG actually references. Anything the
            //    catalog does not name is not runtime art and is none of this tool's business.
            var keys = ReadCatalogArtKeys();
            if (keys.Count == 0)
            {
                Debug.LogError("[Migrate] catalog produced ZERO art keys — refusing to move anything. " +
                               "A migration that cannot see its inputs must not guess at them.");
                return;
            }
            Debug.Log($"[Migrate] catalog references {keys.Count} art key(s).");

            // 2) Resolve each key to an asset path, then take the FULL DEPENDENCY CLOSURE.
            var roots = new Dictionary<string, string>();   // key -> asset path
            var missing = new List<string>();
            foreach (var key in keys)
            {
                string path = ResolveResourcesKey(key);
                if (string.IsNullOrEmpty(path)) { missing.Add(key); continue; }
                roots[key] = path;
            }

            if (missing.Count > 0)
            {
                // Not fatal: some catalog keys legitimately point at pack prefabs that are absent on
                // a fresh clone (CLAUDE.md §4 — LogWarning, never throw). But say so loudly, because
                // a key that cannot be resolved also cannot be migrated, and would then be the ONE
                // building that still loads from Resources after the move.
                Debug.LogWarning($"[Migrate] {missing.Count} catalog key(s) do not resolve to an asset and " +
                                 $"will NOT be migrated: {string.Join(", ", missing)}");
            }

            // ⛔ .fbm FOLDERS MOVE AS A UNIT, NEVER FILE-BY-FILE.
            // Unity treats a "<name>.fbm" folder as OWNED BY its FBX (it is the FBX SDK's unpacked
            // embedded-media folder), and AssetDatabase.MoveAsset REFUSES to move individual files
            // out of one. The first live run learned this the expensive way: 20 FBXs moved while
            // all 66 of their .fbm texture files failed, stranding the folders in Resources and
            // leaving every one of those models without its textures. So .fbm CONTENTS are excluded
            // from the per-file entry list here, and the folder is moved whole after its FBX.
            var closure = new SortedSet<string>(System.StringComparer.OrdinalIgnoreCase);
            foreach (var kv in roots)
            {
                closure.Add(kv.Value);
                foreach (var dep in AssetDatabase.GetDependencies(kv.Value, recursive: true))
                {
                    // Only things currently UNDER Resources are a payload problem. A dependency that
                    // already lives outside Resources is fine where it is — moving it would be churn
                    // with no size benefit and extra reference risk.
                    if (!dep.StartsWith(ResourcesRoot, System.StringComparison.OrdinalIgnoreCase)) continue;
                    // Skip anything inside a .fbm — it rides with its FBX (see the note above).
                    if (dep.IndexOf(".fbm/", System.StringComparison.OrdinalIgnoreCase) >= 0) continue;
                    closure.Add(dep);
                }
            }

            // 3) What stays behind, and WHY it matters: anything left under Resources that still
            //    references a moved asset would drag it back into the payload. Report the overlap so
            //    a partial move is visible instead of silently defeating the migration.
            var stayed = System.IO.Directory
                .GetFiles(ResourcesRoot, "*", System.IO.SearchOption.AllDirectories)
                .Select(p => p.Replace('\\', '/'))
                .Where(p => !p.EndsWith(".meta") && !closure.Contains(p))
                .ToList();

            var leakers = new List<string>();
            foreach (var s in stayed)
            {
                foreach (var dep in AssetDatabase.GetDependencies(s, recursive: true))
                {
                    if (dep != s && closure.Contains(dep)) { leakers.Add($"{s} -> {dep}"); break; }
                }
            }

            Debug.Log($"[Migrate] closure = {closure.Count} asset(s) to move; {stayed.Count} file(s) stay.");
            if (leakers.Count > 0)
            {
                Debug.LogError($"[Migrate] ⛔ {leakers.Count} asset(s) STAYING in Resources still reference a " +
                               "MOVED asset. Unity pulls dependencies of Resources assets back into the payload " +
                               "WHEREVER THEY LIVE, so these would silently undo the migration while every gate " +
                               "stays green. Fix the closure before running LIVE:");
                foreach (var l in leakers.Take(15)) Debug.LogError($"[Migrate]     {l}");
                if (!dryRun)
                {
                    Debug.LogError("[Migrate] ABORTED — refusing to perform a move that is already known to leak.");
                    return;
                }
            }

            long bytes = closure.Sum(p => SafeLen(p));
            Debug.Log($"[Migrate] closure size = {bytes / 1048576.0:F1} MB (this is what leaves the Resources payload).");

            // 4) Build the manifest. In DRY RUN it is written but nothing moves, so the exact plan
            //    can be reviewed as data before any file is touched.
            var entries = new List<MoveEntry>();
            foreach (var src in closure)
            {
                string rel  = src.Substring(ResourcesRoot.Length).TrimStart('/');
                string dst  = $"{ArtRoot}/{rel}";
                string addr = "Structures/" + System.IO.Path.ChangeExtension(rel, null).Replace('\\', '/');
                entries.Add(new MoveEntry
                {
                    address     = addr,
                    resourcesKey= roots.FirstOrDefault(kv => kv.Value == src).Key,
                    from        = src,
                    to          = dst,
                    guid        = AssetDatabase.AssetPathToGUID(src),
                    bytes       = SafeLen(src),
                });
            }

            WriteManifest(entries, dryRun, bytes);

            if (dryRun)
            {
                Debug.Log($"[Migrate] DRY RUN complete — NOTHING MOVED. Manifest written to {ManifestPath} for review.");
                Debug.Log($"{DryMarker} {entries.Count} planned, {bytes / 1048576.0:F1} MB, {leakers.Count} leak(s)");
                return;
            }

            // ================= LIVE MOVE =================
            // Reached only when the leak check above found ZERO staying-assets referencing the
            // closure — otherwise Execute has already returned. That ordering is deliberate: a
            // partial move is worse than none, because it relocates files, reports success, and
            // leaves the payload unchanged.
            var settings = UnityEditor.AddressableAssets.AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null)
            {
                Debug.LogError("[Migrate] Addressables settings not found — ABORTED before moving anything. " +
                               "Moving assets out of Resources without an Addressables home would make every " +
                               "one of them unloadable.");
                return;
            }

            var group = settings.FindGroup(GroupName) ?? settings.CreateGroup(
                GroupName, setAsDefaultGroup: false, readOnly: false, postEvent: false,
                schemasToCopy: null,
                types: new[] { typeof(UnityEditor.AddressableAssets.Settings.GroupSchemas.BundledAssetGroupSchema),
                               typeof(UnityEditor.AddressableAssets.Settings.GroupSchemas.ContentUpdateGroupSchema) });

            EnsureFolder(ArtRoot);

            int moved = 0, failed = 0;
            AssetDatabase.StartAssetEditing();
            try
            {
                foreach (var e in entries)
                {
                    EnsureFolder(System.IO.Path.GetDirectoryName(e.to).Replace('\\', '/'));

                    // MoveAsset PRESERVES the GUID, so every prefab/material/scene reference to this
                    // asset survives. Only hardcoded STRING paths break — which is exactly what the
                    // manifest exists to fix.
                    string err = AssetDatabase.MoveAsset(e.from, e.to);
                    if (!string.IsNullOrEmpty(err))
                    {
                        failed++;
                        Debug.LogError($"[Migrate] MoveAsset FAILED '{e.from}' -> '{e.to}': {err}");
                        continue;
                    }
                    moved++;
                }
            }
            finally
            {
                AssetDatabase.StopAssetEditing();
                AssetDatabase.Refresh();
            }

            if (failed > 0)
            {
                Debug.LogError($"[Migrate] {failed} move(s) FAILED — the tree is now PARTIALLY migrated. " +
                               "Do not build; resolve the failures and re-run.");
            }

            // Mark AFTER the move: the address must point at the asset's NEW location, and marking
            // first would register a path that is about to become wrong.
            int marked = 0;
            foreach (var e in entries)
            {
                string guid = AssetDatabase.AssetPathToGUID(e.to);
                if (string.IsNullOrEmpty(guid)) continue;
                var entry = settings.CreateOrMoveEntry(guid, group, readOnly: false, postEvent: false);
                if (entry == null) continue;
                entry.SetAddress(e.address, postEvent: false);
                marked++;
            }
            settings.SetDirty(UnityEditor.AddressableAssets.Settings.AddressableAssetSettings
                                  .ModificationEvent.BatchModification, null, true, true);
            AssetDatabase.SaveAssets();

            Debug.Log($"[Migrate] moved {moved}/{entries.Count}, marked {marked} addressable in group '{GroupName}'.");

            // Rewrite the manifest in LIVE mode so it records reality, not the plan.
            WriteManifest(entries, dryRun: false, bytes);

            Debug.Log($"{OkMarker} moved {moved}, marked {marked}, {bytes / 1048576.0:F1} MB out of Resources");
        }

        // ---------------------------------------------------------------------

        /// <summary>
        /// Writes the manifest for a FOLDER move: one entry describing the relocation, plus the
        /// counts that prove nothing was lost.
        /// <para>
        /// The per-file manifest served the abandoned per-file strategy. A folder move has exactly
        /// one fact to record — old root, new root — and recording 114 imaginary per-file moves
        /// instead would be a second source of truth that is wrong on the day it is written.
        /// </para>
        /// </summary>
        private static void WriteFolderManifest(int before, int after, int marked)
        {
            var sb = new System.Text.StringBuilder();
            sb.AppendLine("{");
            sb.AppendLine("  \"_generated\": \"DeNelle.Editor.StructureAddressablesMigrator.MoveFolder — DO NOT HAND-EDIT.\",");
            sb.AppendLine("  \"_why\": \"Structure art moved OUT of Resources (force-included in every build) into an Addressable group served from Cloudflare R2. Editor scripts read the new root from here rather than hardcoding it, so a future relocation is one regeneration instead of ~16 edits.\",");
            sb.AppendLine("  \"_mode\": \"LIVE_FOLDER_MOVE\",");
            sb.AppendLine($"  \"_filesBefore\": {before},");
            sb.AppendLine($"  \"_filesAfter\": {after},");
            sb.AppendLine($"  \"_addressableEntries\": {marked},");
            sb.AppendLine("  \"moves\": [");
            sb.AppendLine("    { \"address\": \"<folder>\", \"resourcesKey\": \"Structures/\", " +
                          $"\"from\": \"{ResourcesRoot}\", \"to\": \"{ArtRoot}\", \"guid\": \"\", \"bytes\": 0 }}");
            sb.AppendLine("  ]");
            sb.AppendLine("}");
            System.IO.File.WriteAllText(ManifestPath, sb.ToString());
            AssetDatabase.Refresh();
            Debug.Log($"[Migrate] manifest rewritten as a single folder move: {ResourcesRoot} -> {ArtRoot}");
        }

        /// <summary>Creates a folder chain if absent. MoveAsset fails outright on a missing parent.</summary>
        private static void EnsureFolder(string folder)
        {
            if (string.IsNullOrEmpty(folder) || AssetDatabase.IsValidFolder(folder)) return;
            string parent = System.IO.Path.GetDirectoryName(folder).Replace('\\', '/');
            EnsureFolder(parent);
            AssetDatabase.CreateFolder(parent, System.IO.Path.GetFileName(folder));
        }

        private static long SafeLen(string assetPath)
        {
            try { return new System.IO.FileInfo(assetPath).Length; } catch { return 0; }
        }

        /// <summary>Resolve a Resources key ("Structures/Forge") to its asset path, any extension.</summary>
        private static string ResolveResourcesKey(string key)
        {
            string stem = $"{ResourcesRoot}/{key.Substring("Structures/".Length)}";
            foreach (var ext in new[] { ".prefab", ".fbx", ".png", ".jpg", ".jpeg", ".asset", ".mat" })
            {
                string p = stem + ext;
                if (System.IO.File.Exists(p)) return p;
            }
            return null;
        }

        private static List<string> ReadCatalogArtKeys()
        {
            var keys = new SortedSet<string>(System.StringComparer.OrdinalIgnoreCase);
            if (!System.IO.File.Exists(CatalogPath)) return keys.ToList();

            string json = System.IO.File.ReadAllText(CatalogPath);
            foreach (System.Text.RegularExpressions.Match m in
                     System.Text.RegularExpressions.Regex.Matches(json, "\"(Structures/[^\"]+)\""))
            {
                keys.Add(m.Groups[1].Value);
            }
            return keys.ToList();
        }

        private static void WriteManifest(List<MoveEntry> entries, bool dryRun, long bytes)
        {
            var sb = new System.Text.StringBuilder();
            sb.AppendLine("{");
            sb.AppendLine("  \"_generated\": \"DeNelle.Editor.StructureAddressablesMigrator — DO NOT HAND-EDIT.\",");
            sb.AppendLine("  \"_why\": \"Records every asset relocated out of Resources: its old Resources key, old and new paths, GUID and Addressable address. Editor scripts read THIS instead of hardcoding a Resources path, so a future move is one regeneration rather than ~14 edits. A gate asserts every entry still resolves — a stale manifest must FAIL loudly, never render nothing in game.\",");
            sb.AppendLine($"  \"_mode\": \"{(dryRun ? "DRY_RUN — nothing was moved" : "LIVE")}\",");
            sb.AppendLine($"  \"_totalBytes\": {bytes},");
            sb.AppendLine($"  \"_count\": {entries.Count},");
            sb.AppendLine("  \"moves\": [");
            for (int i = 0; i < entries.Count; i++)
            {
                var e = entries[i];
                sb.Append("    { ");
                sb.Append($"\"address\": \"{e.address}\", ");
                sb.Append($"\"resourcesKey\": \"{e.resourcesKey}\", ");
                sb.Append($"\"from\": \"{e.from}\", ");
                sb.Append($"\"to\": \"{e.to}\", ");
                sb.Append($"\"guid\": \"{e.guid}\", ");
                sb.Append($"\"bytes\": {e.bytes}");
                sb.AppendLine(i < entries.Count - 1 ? " }," : " }");
            }
            sb.AppendLine("  ]");
            sb.AppendLine("}");

            System.IO.File.WriteAllText(ManifestPath, sb.ToString());
            AssetDatabase.Refresh();
            Debug.Log($"[Migrate] manifest written: {ManifestPath} ({entries.Count} entries)");
        }

        private struct MoveEntry
        {
            public string address;
            public string resourcesKey;
            public string from;
            public string to;
            public string guid;
            public long   bytes;
        }
    }
}
