// =============================================================================
// RpgUiCatalog — runtime, WebGL-safe accessor for the owner's polished RPG UI
// sprite pack ("Tech hud elements"). Mirrors ItemIconCatalog / VillageHud's
// HUD-icon loader pattern EXACTLY: the sprites are mirrored into Resources by the
// editor importer (DeNelle.Editor.RpgUiImporter) under Resources/RpgUi/<role>/...,
// and at runtime we lazily Resources.LoadAll<Sprite>("RpgUi/<role>") into a
// name->Sprite dictionary per role. No AssetDatabase / StreamingAssets / File IO
// → safe on every target including WebGL.
// -----------------------------------------------------------------------------
// Assembly: DeNelle.Core   Namespace: DeNelle.Core.UI
//
// SPRITE-FIRST CONTRACT: every Get*/TryGet returns a sprite when the pack art is
// present, or NULL when it is not (pack not imported, role empty). EVERY caller is
// expected to keep its existing procedural/glyph fallback for the null case — so
// the UI is correct whether or not the art is on disk. This catalog NEVER throws
// to a caller (all IO is wrapped) and caches results so repeated lookups are free.
//
// ROLE FOLDERS (populated by RpgUiImporter; see its role->file map):
//   bars/        — ornate gold-frame bar backgrounds + colored fills (HP/MP/XP/ATB)
//   icons/       — bronze-on-parchment RPG action icons (settings/inventory/talk/quest/...)
//   potion/      — framed magic-bottle potions (health/mana/...)
//   badge/       — level / rank badges
//   button/      — play / healing button frames
//   panel/       — menu-bar / profile / score / inventory / quest panel frames
//
// Each role is a flat folder of single-Sprite PNGs; we index every sprite by its
// asset name (lower-cased) so a caller can address a specific one (e.g. "b1" for
// the red potion) OR just take the first via Get(role) for a representative frame.
// =============================================================================

using System.Collections.Generic;
using UnityEngine;
using DeNelle.Core.Diagnostics;

namespace DeNelle.Core.UI
{
    /// <summary>
    /// Runtime catalog for the RPG UI sprite pack mirrored to Resources/RpgUi.
    /// All lookups are sprite-first with a null return when the art is absent
    /// (callers keep their procedural fallback). WebGL-safe (Resources only).
    /// </summary>
    public static class RpgUiCatalog
    {
        private const string ResRoot = "RpgUi/";

        // Per-role caches: role -> (spriteName -> Sprite) and role -> ordered list.
        private static readonly Dictionary<string, Dictionary<string, Sprite>> _byName
            = new Dictionary<string, Dictionary<string, Sprite>>(System.StringComparer.OrdinalIgnoreCase);
        private static readonly Dictionary<string, List<Sprite>> _ordered
            = new Dictionary<string, List<Sprite>>(System.StringComparer.OrdinalIgnoreCase);

        // ── Canonical role names (kept in lockstep with RpgUiImporter folders) ──
        public const string RoleBars   = "bars";
        public const string RoleIcons  = "icons";
        public const string RolePotion = "potion";
        public const string RoleBadge  = "badge";
        public const string RoleButton = "button";
        public const string RolePanel  = "panel";
        public const string RoleSlot   = "slot";
        // Blink "OBSIDIAN UI" roles (mirrored by RpgUiImporter from Assets/Blink):
        public const string RoleFrame      = "frame";       // full ornate obsidian panel backgrounds
        public const string RoleSilhouette = "silhouette";  // paper-doll body silhouettes
        // crown/ — victory-summary tier crowns (font-independent star-rating replacement; the
        // build font had no TMP star glyph, so the 3-star row tofu'd). Art placed at
        // Resources/RpgUi/crown/ by the importer; callers keep the glyph fallback on null.
        public const string RoleCrown      = "crown";
        // HUD_OBSIDIAN_ARCHITECTURE_2026-07-03 §2 roles (populated by BlinkUiImporter, P0):
        public const string RoleHud     = "hud";      // bars / nameplates / cast / target / chat cores
        public const string RoleElement = "element";  // plates, tabs, notifications, toggles, scroll bits

        // ── Resources paths for the NON-sprite Blink assets (P0-mirrored, committed) ──
        /// <summary>Folder (under Resources) of the mirrored Blink uGUI PREFABS — the factory's
        /// LOADER+BINDER primary mode (orchestrator amendment 2026-07-03). Load as
        /// <c>Resources.Load&lt;GameObject&gt;(PrefabRoot + name)</c>; null ⇒ constructed fallback.</summary>
        public const string PrefabRoot = "RpgUi/prefabs/";
        /// <summary>Folder (under Resources) of the TMP font assets generated by BlinkFontImporter.</summary>
        public const string FontRoot = "RpgUi/font/";
        public const string FontTitleAsset = "font_title";   // Merriweather Bold (§1.13)
        // NOTE (owner defect 2026-08-05): the asset currently at this name is Alata Regular,
        // whose numeral 1 is a BARE STEM (7.23 ink units vs its own 'l' 6.84 / '|' 6.14) — see
        // ElarionUiKit's numeral-legibility gate, which REJECTS it at load and falls the Body
        // role through to the default chain. Regenerating it from Alata will not help; the gate
        // clears the moment this name is baked from a face with a flagged 1 (BlinkFontImporter).
        public const string FontBodyAsset  = "font_body";    // Alata Regular
        public const string FontStampAsset = "font_stamp";   // Acme

        // ── hud/ canonical names (§2 HUD_Obsidian table; canonical names are always clean —
        //     source-file typos [STamina/Castt/Potrait/HIUD] die at the importer) ──
        public const string HudBarHealth   = "bar_health";
        public const string HudBarMana     = "bar_mana";
        public const string HudBarEnergy   = "bar_energy";
        public const string HudBarStamina  = "bar_stamina";
        public const string HudBarStatBg   = "bar_stat_bg";
        public const string HudBarStatFill = "bar_stat_fill";   // white — tinted per kind (§1.1 fallback fill)
        public const string HudBarCast1    = "bar_cast_1";
        public const string HudBarCast2    = "bar_cast_2";
        public const string HudBarCast3    = "bar_cast_3";
        public const string HudBarCastFill = "bar_cast_fill";
        public const string HudBarXp       = "bar_xp";
        public const string HudTargetCore  = "target_core";
        public const string HudNameplateBar           = "nameplate_bar";
        public const string HudNameplateHealth        = "nameplate_health";
        public const string HudNameplateHealthEnemy   = "nameplate_health_enemy";
        public const string HudNameplateHealthNeutral = "nameplate_health_neutral";
        public const string HudNameplateMana          = "nameplate_mana";
        public const string HudNameplatePortrait      = "nameplate_portrait";
        public const string HudNameplateBoss          = "nameplate_boss";
        public const string HudNameplateRare          = "nameplate_rare";
        public const string HudNameplateEnemyBg       = "nameplate_enemy_bg";
        public const string HudNameplateParty         = "nameplate_party";
        public const string HudPortraitBorder = "portrait_border";
        public const string HudCore        = "hud_core";
        public const string HudCoreDiablo  = "hud_core_diablo";
        public const string HudStatOrb     = "stat_orb";
        public const string HudChatCore    = "chat_core";
        public const string HudChatTab     = "chat_tab";
        public const string HudQuestTracker    = "quest_tracker";
        public const string HudQuestTrackerBar = "quest_tracker_bar";
        public const string HudCollapse    = "hud_collapse";
        public const string HudExpand      = "hud_expand";
        public const string HudBlock       = "hud_block";
        public const string HudInteraction = "hud_interaction";
        public const string HudArc1        = "hud_arc_1";
        public const string HudArc2        = "hud_arc_2";

        // ── button/ canonical names (§2 Buttons_Obsidian; the 5x4 family is addressed via
        //     ElarionUiKit.ObsidianButtonSpriteName(style,color) → "button{1..5}_{gray|green|red|yellow}") ──
        public const string ButtonCloseNormal = "close_normal";
        public const string ButtonCloseOn     = "close_on";
        public const string ButtonCloseOff    = "close_off";
        public const string ButtonToggleOn    = "toggle_on";
        public const string ButtonToggleOff   = "toggle_off";
        public const string ButtonSliderBg     = "slider_bg";
        public const string ButtonSliderFill   = "slider_fill";
        public const string ButtonSliderHandle = "slider_handle";
        public const string ButtonDropdown1 = "dropdown_1";
        public const string ButtonDropdown2 = "dropdown_2";
        public const string ButtonDropdown3 = "dropdown_3";
        public const string ButtonNotif1    = "notif_btn_1";
        public const string ButtonNotif2    = "notif_btn_2";
        public const string ButtonPopup     = "popup";
        public const string ButtonChatElement1 = "chat_element_1";
        public const string ButtonChatElement2 = "chat_element_2";
        public const string ButtonChatElement3 = "chat_element_3";
        public const string ButtonChatElement4 = "chat_element_4";
        public const string ButtonMapZoom   = "map_zoom";
        public const string ButtonMapUnzoom = "map_unzoom";
        public const string ButtonArrow     = "arrow";

        // ── element/ canonical names (§2 Elements_Obsidian) ──
        public const string ElementStat    = "element_stat";    // stat/currency chip plate
        public const string ElementBar     = "element_bar";     // wide panel plate
        public const string ElementTab     = "element_tab";
        public const string ElementNotif1  = "notif_1";
        public const string ElementNotif2  = "notif_2";
        public const string ElementNotif4  = "notif_4";
        public const string ElementBar1     = "element_bar_1";
        public const string ElementBar5     = "element_bar_5";
        public const string ElementBar5Fill = "element_bar_5_fill";
        public const string ElementLoadingBg   = "loading_bg";
        public const string ElementLoadingFill = "loading_fill";
        public const string ElementScrollBg = "scroll_bg";
        public const string ElementScrollUp = "scroll_up";
        public const string ElementToggleBoxOn  = "togglebox_on";
        public const string ElementToggleBoxOff = "togglebox_off";
        public const string ElementHandle  = "handle";
        public const string ElementCross   = "cross";
        // WO-1010 D17 (2026-08-09): the two rail-verb glyphs that were missing from the pack —
        // check-mark (confirm) + circular-arrow (rotate), authored in the element/cross style.
        // Same sprite-or-null contract as every other name: callers keep their ASCII fallback.
        public const string ElementCheck   = "check";
        public const string ElementRotate  = "rotate";
        public const string ElementArrowBox   = "arrow_box";
        public const string ElementArrowBoxOn = "arrow_box_on";
        public const string ElementMenuBtn1 = "menu_btn_1";
        public const string ElementMenuBtn2 = "menu_btn_2";
        public const string ElementMenuBtn3 = "menu_btn_3";
        public const string ElementEnchant     = "enchant_element";
        public const string ElementEnchantSlot = "enchant_slot";
        public const string ElementBorderSocket1 = "border_socket_1";  // source "Socketing_Border_!" — typo dies here
        public const string ElementBorderSocket2 = "border_socket_2";
        public const string ElementBorderSocket3 = "border_socket_3";
        public const string ElementBorderSocket4 = "border_socket_4";

        // ── slot/ rarity frames (Rarity_1..5 → rarity_1..5) ──
        /// <summary>Canonical rarity slot-frame name for a 0-based rarity index (0..4 → rarity_1..5).</summary>
        public static string RaritySlotName(int rarityIndex)
        {
            int i = rarityIndex < 0 ? 0 : (rarityIndex > 4 ? 4 : rarityIndex);
            return "rarity_" + (i + 1);
        }

        // frame/ — one ornate obsidian panel background per screen (Simple, preserve-aspect):
        public const string FrameInventory = "frame_inventory";
        public const string FrameCrafting  = "frame_crafting";
        public const string FrameCharacter = "frame_character"; // Stats_Panel
        public const string FrameCore      = "frame_core";
        public const string FrameTalent    = "frame_talent";
        public const string FrameMerchant  = "frame_merchant";
        public const string FrameDialogue  = "frame_dialogue";
        public const string FrameQuest     = "frame_quest";
        public const string FrameSettings  = "frame_settings";
        public const string FrameOptions   = "frame_options";
        public const string FrameLoot      = "frame_loot";
        public const string FramePet       = "frame_pet";
        public const string FrameDialogue2 = "frame_dialogue_2"; // NPC card variant (Dialogue_2_Panel, P0 gap-fill)
        public const string FrameElement   = "frame_element"; // inner sub-plate (9-sliced)
        public const string FrameTextBg    = "frame_textbg";  // inner text background (9-sliced)
        // silhouette/:
        public const string SilMale   = "sil_male";
        public const string SilFemale = "sil_female";
        public const string SilPet    = "sil_pet";
        // slot/ — Obsidian sockets (9-sliced):
        public const string SlotArmor     = "slot_armor";
        public const string SlotCharacter = "slot_character";
        public const string SlotAction    = "slot_action";
        public const string SlotSocket    = "slot_socket";
        // slot/ rarity frames Rarity_1..5 -> rarity_1..5; talent borders -> talent_1..4.

        // ── Well-known sprite names within a role (lockstep with the importer map) ──
        // bars/ (ornate gold-frame bar family — frame bg + matching colored fill):
        public const string BarFrameRed   = "bar_frame_red";    // HP frame (Loading 6 bg)
        public const string BarFillRed    = "bar_fill_red";     // HP fill   (Loading 6 fill)
        public const string BarFrameGreen = "bar_frame_green";  // generic frame (Loading 5 bg)
        public const string BarFillGreen  = "bar_fill_green";   // generic fill  (Loading 5 fill)
        public const string BarFrameBlue  = "bar_frame_blue";   // MP frame  (Loading 7 bg, green-glow socket reused as blue-less; see importer)
        public const string BarFillBlue   = "bar_fill_blue";    // MP fill
        // icons/ (bronze RPG icons):
        public const string IconSettings  = "icon_settings";    // Tab icons/icon 4 (gear)
        public const string IconInventory = "icon_inventory";   // Rpg icons/icon 2 (chest)
        public const string IconTalk      = "icon_talk";        // Rpg icons/icon 6 (person)
        public const string IconQuest     = "icon_quest";       // Rpg icons/icon 8 (map)
        public const string IconSword     = "icon_sword";       // Rpg icons/icon 9
        public const string IconShield    = "icon_shield";      // Rpg icons/icon 5
        public const string IconHeart     = "icon_heart";       // Rpg icons/icon 10
        public const string IconTree      = "icon_tree";        // Rpg icons/icon 3 (campfire → crest stand-in)
        public const string IconCombat    = "icon_combat";      // Rpg icons/icon 7 (sword+axe)
        public const string IconCompass   = "icon_compass";     // Tab icons/icon 2 (star)
        // potion/ (framed magic bottles):
        public const string PotionHealth  = "potion_health";    // Magic bottles/b1 (red)
        public const string PotionMana    = "potion_mana";      // Magic bottles/b2 (blue)
        public const string PotionFire    = "potion_fire";      // Magic bottles/b3 (orange)
        // badge/:
        public const string BadgeLevel    = "badge_level";      // Level badage 1
        // button/:
        public const string ButtonGold    = "button_gold";      // Play buttons/button 3 (gold scroll)
        public const string ButtonConfirm = "button_confirm";   // Obsidian green confirm/buy (Buttons_Obsidian/Button2_Green)
        // panel/:
        public const string PanelBar      = "panel_bar";        // Menu bar 1 (warm gold/red plate)
        public const string PanelTab      = "panel_tab";        // Score tabs/Tab 1 (ornate banner)
        public const string PanelInventory= "panel_inventory";  // Ui Elements/Dialogue (grid panel)
        public const string PanelQuest    = "panel_quest";      // Ui Elements/Quest log
        // panel/ — clean ORNATE window frames (WO-438 screen map), 9-sliced:
        public const string PanelWindow     = "panel_window";      // D8 ornate scrollwork window (dialogue/hero)
        public const string PanelWindowDark = "panel_window_dark"; // D5 clean dark carved frame (neutral default)
        public const string PanelVendor     = "panel_vendor";      // D3 dark-wood vendor board (shop)
        public const string PanelGrid       = "panel_grid";        // D4 grid plate (inventory)
        public const string PanelPortrait   = "panel_portrait";    // Model selection ornate wood portrait frame
        public const string PanelProfile    = "profile_frame";     // Profile tab P1 — gold sunburst portrait medallion + name + 2 bar slots
        // The canonical DEFAULT window frame: a clean, neutral ornate frame every framed
        // window inherits via ElarionUiKit.PanelFramed when no explicit frame is named.
        public const string PanelDefault    = PanelWindowDark;
        // button/ — clean (text-free) framed button + exit, 9-sliced:
        public const string ButtonFrame   = "button_frame";    // D2/Button 1 (neutral framed button)
        public const string ButtonExit    = "button_exit";     // D2/Exit (close/exit button)
        // slot/ — per-item article plate (Blink ArticleSlot/ItemBackground), 9-sliced:
        public const string SlotItem      = "slot_item";       // Slots_Obsidian/Inventory_Slot (per-item plate)
        // crown/ — victory tier crowns (preserve-aspect single sprite). tier1/2/3 map to the
        // earned star count; perfect is the flawless/no-hit capstone crown.
        public const string CrownTier1    = "crown_tier1";
        public const string CrownTier2    = "crown_tier2";
        public const string CrownTier3    = "crown_tier3";
        public const string CrownPerfect  = "crown_perfect";

        /// <summary>
        /// Representative sprite for a role (the first one loaded, by name order), or
        /// null if the role folder is empty / not imported. Callers keep their fallback
        /// on null.
        /// </summary>
        public static Sprite Get(string role)
        {
            EnsureRole(role);
            var list = _ordered.TryGetValue(role, out var l) ? l : null;
            return (list != null && list.Count > 0) ? list[0] : null;
        }

        /// <summary>
        /// A specific named sprite within a role (e.g. role "potion", name "b1"), or
        /// null when absent. Name match is case-insensitive. The well-known name
        /// constants on this class are the importer's canonical names.
        /// </summary>
        public static Sprite Get(string role, string spriteName)
        {
            if (string.IsNullOrEmpty(spriteName)) return Get(role);
            EnsureRole(role);
            var map = _byName.TryGetValue(role, out var m) ? m : null;
            if (map == null) return null;
            return map.TryGetValue(spriteName, out var s) ? s : null;
        }

        /// <summary>True + out-sprite when the named role/sprite art is present.</summary>
        public static bool TryGet(string role, string spriteName, out Sprite sprite)
        {
            sprite = Get(role, spriteName);
            return sprite != null;
        }

        /// <summary>All sprites in a role (empty list when absent). Read-only use.</summary>
        public static IReadOnlyList<Sprite> All(string role)
        {
            EnsureRole(role);
            return _ordered.TryGetValue(role, out var l) ? l : System.Array.Empty<Sprite>();
        }

        // ── Lazy per-role load (WebGL-safe; cached; never throws to the caller) ──
        private static void EnsureRole(string role)
        {
            if (string.IsNullOrEmpty(role) || _ordered.ContainsKey(role)) return;

            FlowTrace.Step("RpgUi", $"EnsureRole '{role}' -> LoadAll Resources/{ResRoot}{role}");
            var map = new Dictionary<string, Sprite>(System.StringComparer.OrdinalIgnoreCase);
            var list = new List<Sprite>();
            Sprite[] subs = null;
            try { subs = Resources.LoadAll<Sprite>(ResRoot + role); }
            catch (System.Exception e)
            {
                // Hard load fault — error level so it lands in break-log (was Debug.LogWarning only).
                FlowTrace.Fail("RpgUi", $"LoadAll FAILED for role '{role}': {e.GetType().Name}: {e.Message}");
                Debug.LogWarning("[RpgUiCatalog] load failed for role '" + role + "': " + e.Message);
            }
            if (subs != null)
            {
                Guard.TryEach("RpgUi", $"index sprite (role '{role}')", subs, sp =>
                {
                    if (sp == null || string.IsNullOrEmpty(sp.name)) return;
                    if (!map.ContainsKey(sp.name)) map[sp.name] = sp;
                    list.Add(sp);
                });
            }
            _byName[role] = map;
            _ordered[role] = list;
            if (list.Count == 0)
            {
                // Fallback/anomaly: role folder empty or not imported -> callers keep procedural glyph.
                FlowTrace.Warn("RpgUi", $"role '{role}' resolved 0 sprites (Resources/{ResRoot}{role} " +
                    "empty/not imported) -> callers use procedural fallback");
                Debug.Log("[RpgUiCatalog] no sprites under Resources/" + ResRoot + role +
                          " — run Defenders/Art/Import RPG UI Pack. Callers keep procedural fallback.");
            }
            else
            {
                FlowTrace.Step("RpgUi", $"role '{role}' indexed {list.Count} sprite(s)");
            }
        }

#if UNITY_EDITOR
        /// <summary>Editor-only: drop caches so a re-import is picked up without a domain reload.</summary>
        public static void ClearCache()
        {
            _byName.Clear();
            _ordered.Clear();
        }
#endif
    }
}
