// =============================================================================
// CraftingStationInjector — runtime, NON-DESTRUCTIVE placement of the Apothecary
// consumable-crafting station in the castle hub. Opens PanelId.ConsumableCrafting.
// -----------------------------------------------------------------------------
// WHY a runtime injector (not a scene edit / regen):
//   PanelId.ConsumableCrafting -> CraftingPanelMvvm is registered, but nothing in
//   the world opens it (no apothecary building exists). The castle is regenerated by
//   CastleHubBuilder and re-saving / regenerating MainCastle_Hall.unity to drop a
//   building in carries the scene-resave corruption risk (CLAUDE.md §3) AND canonical
//   placement is owner-deferred. So this self-bootstrapping DDOL singleton spawns ONE
//   "Apothecary" station at load — WITHOUT ever touching the .unity file or
//   CastleHubBuilder. Idempotent per load, gated to the castle/home hub.
//
// WHAT IT BUILDS (mirrors the proven CastleVendorNpcInjector / CompanionIntroducer
// runtime-injection shape):
//   A station GameObject at a tweakable courtyard const, with a Building
//   (Type=ApothecaryWorkbench, BuildingId="apothecary", DisplayLabel="Apothecary")
//   + a BuildingInteractable (the same proximity-prompt the other buildings use).
//   Walking up + interacting opens PanelId.ConsumableCrafting DIRECTLY — apothecary
//   returns null from StructureHookIdFor, so Interact() falls through the Yarn path to
//   TryPanelFor -> ConsumableCrafting (no Yarn detour).
//
// VISUAL: reuses VisualFactory.Skin (the SAME Resources structure-model loader the
//   castle storefronts use via HubStructureVisualInjector) with a candidate house/
//   stall model; on a pack-missing clone it Guards down to a simple placeholder cube
//   (Debug.LogWarning, never error — CLAUDE.md §4). The interaction works either way.
//
// Village -> Core only; code-spawn only, no scene hand-edit. Null-guarded throughout.
// =============================================================================

using DeNelle.Core;
using DeNelle.Core.Diagnostics;
using UnityEngine;
using UnityEngine.AI;
using UnityEngine.SceneManagement;

namespace DeNelle.Village
{
    /// <summary>Runtime, non-destructive placement of the Apothecary consumable-crafting
    /// station in the castle hub. Walk up + interact -> PanelId.ConsumableCrafting.</summary>
    public sealed class CraftingStationInjector : MonoBehaviour
    {
        public static CraftingStationInjector Instance { get; private set; }

        /// <summary>Stable id — kept apothecary-free of Yarn (StructureHookIdFor returns null
        /// for it, so the building opens the panel directly).</summary>
        private const string StationId = "apothecary";
        private const string StationLabel = "Apothecary";

        private const string HolderName = "ApothecaryStation (runtime)";

        // TWEAK: courtyard placement for the Apothecary, in MainCastle_Hall world space.
        // The hero spawns near the Tree of Life (~0,y,-11) and the Heart sits at (0,0,12);
        // the storefront ring rings the courtyard. This is a free spot off to the east of
        // the courtyard, snapped to the navmesh below so it's reachable. Move freely — the
        // canonical placement is owner-deferred.
        private static readonly Vector3 StationPos = new Vector3(11f, 0f, 2f);

        // Candidate Resources structure models (same source as the castle storefronts —
        // see HubStructureVisualInjector). First that loads wins; all-miss -> cube.
        private static readonly string[] CandidateModels =
        {
            "Structures/store",
            "Structures/jeweler",
            "Structures/Forge",
            "Structures/lumbermill",
        };

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        private static void Bootstrap()
        {
            if (Instance != null) return;
            new GameObject("CraftingStationInjector").AddComponent<CraftingStationInjector>();
        }

        private void Awake()
        {
            if (Instance != null && Instance != this) { Destroy(gameObject); return; }
            Instance = this;
            DontDestroyOnLoad(gameObject);

            SceneManager.sceneLoaded -= OnSceneLoaded;
            SceneManager.sceneLoaded += OnSceneLoaded;

            if (HubScenes.IsHub(SceneManager.GetActiveScene().name)) Inject();
        }

        private void OnDestroy()
        {
            if (Instance == this) Instance = null;
            SceneManager.sceneLoaded -= OnSceneLoaded;
        }

        private void OnSceneLoaded(Scene scene, LoadSceneMode mode)
        {
            if (HubScenes.IsHub(scene.name)) Inject();
        }

        private void Inject()
        {
            using var _ = FlowTrace.Enter("Crafting", "CraftingStationInjector.Inject");

            // Idempotent: if an apothecary already exists (a baked building or a prior runtime
            // holder), do NOT spawn a second one.
            if (AlreadyPresent())
            {
                FlowTrace.Step("Crafting", "apothecary station already present — no-op (idempotent).");
                return;
            }

            // Snap the const to the navmesh so the station is reachable / seated on the floor.
            Vector3 pos = StationPos;
            if (NavMesh.SamplePosition(pos, out var hit, 12f, NavMesh.AllAreas))
                pos = hit.position;

            var holder = new GameObject(HolderName);
            holder.transform.position = pos;

            // VISUAL — reuse the castle's Resources structure-model loader; Guard down to a
            // placeholder cube on a pack-missing clone (LogWarning, never error — §4).
            AttachVisual(holder);

            // BEHAVIOUR — Building first (BuildingInteractable RequireComponent<Building>), then
            // the proximity-prompt interactable. Configure() sets the type/id/label and adds the
            // AABB blocker so the hero paths around it like a real building.
            Building building = null;
            Guard.Try("Crafting", "add+configure Building (apothecary)", () =>
            {
                building = holder.AddComponent<Building>();
                building.Configure(BuildingType.ApothecaryWorkbench, StationId, StationLabel);
            });
            if (building == null)
            {
                FlowTrace.Fail("Crafting",
                    "failed to add Building to apothecary station — destroying holder (no half-built station).");
                Destroy(holder);
                return;
            }

            Guard.Try("Crafting", "add BuildingInteractable (apothecary)",
                () => holder.AddComponent<BuildingInteractable>());

            FlowTrace.Step("Crafting",
                $"spawned Apothecary station at {pos} (id='{StationId}') -> opens PanelId.ConsumableCrafting on interact.");
            Debug.Log($"[CraftingStationInjector] spawned Apothecary station at {pos} " +
                      "(walk up + interact -> consumable crafting panel).");
        }

        /// <summary>True if an apothecary station already exists in-scene — a prior runtime holder
        /// OR any Building whose id/label marks it the apothecary. Keeps Inject idempotent.</summary>
        private static bool AlreadyPresent()
        {
            if (GameObject.Find(HolderName) != null) return true;
            foreach (var b in FindObjectsByType<Building>(FindObjectsSortMode.None))
            {
                if (b == null) continue;
                if (b.Type == BuildingType.ApothecaryWorkbench) return true;
                string id = (b.BuildingId ?? "").ToLowerInvariant();
                if (id.Contains("apothecary")) return true;
            }
            return false;
        }

        // ── Visual (reuse VisualFactory.Skin; placeholder cube fallback) ──────
        private static void AttachVisual(GameObject holder)
        {
            GameObject visual = null;
            foreach (var path in CandidateModels)
            {
                // Tripo FBX exports import lying on their side at identity (the "standard tripo
                // issue" — owner F8 "apothecary on its side"). Apply the SAME upright correction
                // every other hub structure gets via HubStructureVisualInjector: pitch -90 (stand
                // up) + yaw 90 (face the plaza), matching the 'store' swap row. This path was the
                // lone hub structure that skinned at identity and bypassed the convention.
                //
                // SEATING (owner F8 "apothecary is right way now, just everything is off ground"):
                // Structure(..) already sets SeatOnGround=true, which Skin runs AFTER applying
                // LocalRotation + Fit — so the upright model's bounds-BASE lands exactly on the
                // holder's ground y. The prior post-Skin `localScale *= 0.7` + `localPosition.y = 0`
                // UNDID that seat (scaling lifts the bounds-base off the pivot; y=0 wipes the seat
                // offset) → the model floated. Fix = bake the 0.7 size into the FIT (6 * 0.7 = 4.2)
                // so SeatOnGround measures the final size, and do NOT touch the transform afterwards.
                var opts = SkinOptions.Structure(6f * 0.7f);
                opts.LocalRotation = Quaternion.Euler(-90f, 90f, 0f);
                visual = Guard.Try("Crafting", $"skin apothecary visual '{path}'",
                    () => VisualFactory.Skin(holder.transform, path, opts),
                    fallback: null);
                if (visual != null)
                {
                    FlowTrace.Step("Crafting", $"apothecary visual resolved from '{path}' (upright -90/+90, fit 4.2m, seated on ground).");
                    return;
                }
            }

            // Pack-missing clone (Resources structure models absent): keep the station VISIBLE
            // + interactable with a simple placeholder cube. Warn, never error (§4).
            FlowTrace.Warn("Crafting",
                "no apothecary structure model resolved (Resources/Structures pack may be absent) — placeholder cube used.");
            Debug.LogWarning("[CraftingStationInjector] no apothecary model found — placeholder cube used.");
            var cube = GameObject.CreatePrimitive(PrimitiveType.Cube);
            cube.name = "Apothecary_Placeholder";
            cube.transform.SetParent(holder.transform, false);
            cube.transform.localPosition = Vector3.up * 1f;
            cube.transform.localScale = new Vector3(2f, 2f, 2f);
            // Non-blocking placeholder — the Building's own AABB blocker handles pathing.
            var col = cube.GetComponent<Collider>();
            if (col != null) col.isTrigger = true;
            // WO-580 (owner F8 "stray white bar/box in front of me, nothing there"): a raw
            // GameObject.CreatePrimitive leaves the renderer on Unity's DEFAULT material,
            // which renders FLAT WHITE under URP — exactly the stray white box the owner saw
            // on a lean / pack-missing build. Tint it a neutral warm stone so it reads as an
            // obvious placeholder block, never a jarring white bar. Never magenta (URP/Lit).
            TintPlaceholderStone(cube, "Apothecary_Placeholder");
        }

        // WO-580: give a fallback placeholder primitive a neutral stone material so the bare
        // CreatePrimitive default-white material never shows as a stray white box/bar in the
        // hub. URP/Lit (Standard fallback for non-URP editor); null-safe; FlowTrace-proven.
        private static void TintPlaceholderStone(GameObject go, string label)
        {
            if (go == null) return;
            var r = go.GetComponent<MeshRenderer>();
            if (r == null) return;
            var sh = Shader.Find("Universal Render Pipeline/Lit") ?? Shader.Find("Standard");
            if (sh == null) return;
            var mat = new Material(sh) { name = "PlaceholderStone (runtime)" };
            var stone = new Color(0.32f, 0.30f, 0.28f, 1f); // neutral warm stone — not white
            if (mat.HasProperty("_BaseColor")) mat.SetColor("_BaseColor", stone);
            if (mat.HasProperty("_Color")) mat.SetColor("_Color", stone);
            r.sharedMaterial = mat;
            FlowTrace.Step("Crafting",
                "WO-580: tinted '" + label + "' placeholder cube to neutral stone " +
                "(was default-white CreatePrimitive material → stray white box).");
        }
    }
}
