// =============================================================================
// ModelCatalogGenerator — reproducible, headless dump of every runtime-loadable
// model under Assets/Resources (Enemies / Structures / Heroes / Towers).
// -----------------------------------------------------------------------------
// WHY: the hand-curated docs/MODEL_CATALOG.md carries the *mappings* (which id →
// which model, plus findings). This generator carries the *ground truth* — the
// exact files on disk — so the curated doc can be checked against reality at any
// time (the BUG#22 class: a catalog pointing at a name that isn't there). It is
// READ-ONLY over assets (AssetDatabase.FindAssets + path reads only) and writes
// a single markdown file: docs/MODEL_CATALOG.generated.md.
//
// Run from the menu (Defenders > Catalog > Regenerate Model Catalog) or headless:
//   -executeMethod DeNelle.Editor.Catalog.ModelCatalogGenerator.Generate
// =============================================================================

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace DeNelle.Editor.Catalog
{
    /// <summary>Scans Resources model folders and writes docs/MODEL_CATALOG.generated.md.</summary>
    public static class ModelCatalogGenerator
    {
        private const string OutputPath = "docs/MODEL_CATALOG.generated.md";

        // Resources-relative folders that hold runtime-loadable models, with the
        // asset extensions that count as a loadable model in each.
        private static readonly (string resFolder, string assetFolder, string[] exts, string note)[] Targets =
        {
            ("Enemies",    DeNelle.Core.AssetRoots.EnemyContent,    new[] { ".prefab", ".fbx" }, "Loaded by EnemyFactory.ModelForEnemy → VisualFactory.Skin(\"Enemies/<Name>\")"),
            ("Structures", DeNelle.Core.AssetRoots.StructureContent, new[] { ".prefab" },         "Loaded by StructureFactory from structures-catalog.json visualPrefabPath"),
            ("Heroes",     "Assets/Resources/Heroes",     new[] { ".prefab", ".fbx" }, "Loaded by Resources.Load<GameObject>(\"Heroes/<slug>\") — slug = Knight/Mage/Ranger/Cleric"),
            ("Towers",     "Assets/Resources/Towers",     new[] { ".asset" },          "TowerData ScriptableObjects (data, not models) — upgrades[].visualPrefab are GUID refs"),
        };

        [MenuItem("Defenders/Catalog/Regenerate Model Catalog")]
        public static void Generate()
        {
            var sb = new StringBuilder();
            sb.AppendLine("# MODEL_CATALOG (generated) — runtime-loadable models on disk");
            sb.AppendLine();
            sb.AppendLine("> AUTO-GENERATED by `DeNelle.Editor.Catalog.ModelCatalogGenerator.Generate`.");
            sb.AppendLine("> Do NOT hand-edit — re-run *Defenders > Catalog > Regenerate Model Catalog*.");
            sb.AppendLine("> The curated mappings + findings live in `docs/MODEL_CATALOG.md`; this file");
            sb.AppendLine("> is the pure disk inventory used to check that doc against reality (BUG#22 class).");
            sb.AppendLine();
            sb.AppendLine($"**Generated:** {DateTime.Now:yyyy-MM-dd HH:mm}");
            sb.AppendLine();

            int grandTotal = 0;

            foreach (var (resFolder, assetFolder, exts, note) in Targets)
            {
                sb.AppendLine($"## Resources/{resFolder}");
                sb.AppendLine();
                sb.AppendLine(note);
                sb.AppendLine();

                if (!AssetDatabase.IsValidFolder(assetFolder))
                {
                    sb.AppendLine($"_(folder `{assetFolder}` not found — skipped)_");
                    sb.AppendLine();
                    continue;
                }

                var rows = CollectModels(assetFolder, exts, resFolder);
                grandTotal += rows.Count;

                sb.AppendLine($"**Count: {rows.Count}**");
                sb.AppendLine();
                sb.AppendLine("| File | Resources path |");
                sb.AppendLine("|---|---|");
                foreach (var (fileName, resPath) in rows)
                    sb.AppendLine($"| `{fileName}` | `{resPath}` |");
                sb.AppendLine();
            }

            sb.AppendLine("---");
            sb.AppendLine();
            sb.AppendLine($"**Grand total loadable models: {grandTotal}**");

            string fullPath = Path.GetFullPath(OutputPath);
            Directory.CreateDirectory(Path.GetDirectoryName(fullPath));
            File.WriteAllText(fullPath, sb.ToString());

            Debug.Log($"[ModelCatalogGenerator] Wrote {grandTotal} models to {OutputPath}");
            AssetDatabase.Refresh();
        }

        /// <summary>Returns (fileName, Resources-relative-path-without-extension) for each
        /// model in the folder (top level only — matches Resources.Load addressing).</summary>
        private static List<(string fileName, string resPath)> CollectModels(
            string assetFolder, string[] exts, string resFolder)
        {
            var result = new List<(string, string)>();

            // FindAssets walks recursively; restrict to the immediate folder so the
            // listed path matches the flat "<resFolder>/<Name>" address callers use.
            string[] guids = AssetDatabase.FindAssets(string.Empty, new[] { assetFolder });
            var seen = new HashSet<string>();

            foreach (string guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (string.IsNullOrEmpty(path)) continue;

                // Top level only: parent folder must equal the target folder.
                string parent = Path.GetDirectoryName(path).Replace('\\', '/');
                if (!string.Equals(parent, assetFolder, StringComparison.OrdinalIgnoreCase))
                    continue;

                string ext = Path.GetExtension(path).ToLowerInvariant();
                if (!exts.Contains(ext)) continue;

                string fileName = Path.GetFileName(path);
                if (!seen.Add(fileName)) continue;

                string nameNoExt = Path.GetFileNameWithoutExtension(path);
                result.Add((fileName, $"{resFolder}/{nameNoExt}"));
            }

            result.Sort((a, b) => string.Compare(a.Item1, b.Item1, StringComparison.OrdinalIgnoreCase));
            return result;
        }
    }
}
