// WO-1067 static inventory. Static evidence never certifies a weapon visually.
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const read = name => JSON.parse(fs.readFileSync(path.join(root, 'Assets/Resources/Data/Canonical', name), 'utf8'));
const weapons = read('weapons.json').weapons || [];
const armor = read('armor.json').armor || [];
const existsResource = key => {
  if (!key) return false;
  const base = path.join(root, 'Assets/Resources', key);
  return ['.png', '.jpg', '.jpeg', '.prefab', '.fbx', ''].some(ext => fs.existsSync(base + ext));
};
const esc = value => String(value == null ? '' : value).replace(/\|/g, '\\|').replace(/[\r\n]+/g, ' ');
let out = '# Gear visual-readiness inventory — 2026-08-22\n\n';
out += 'Generated by `node tools/gear_readiness_report.js`. Static checks are inventory evidence only. '; 
out += 'They never promote a weapon to `Ready`; owner-reviewed contact-sheet evidence is required. '; 
out += 'Orientation must use real-vertex end spread (`GearVisualGeometryAudit`), because opposite rotations can have identical AABBs.\n\n';
out += '## Weapons\n\n| id | icon | model reference | authored state | evidence/failure |\n|---|---|---|---|---|\n';
for (const w of weapons) {
  const icon = w.iconPath ? (existsResource(w.iconPath) ? 'authored + found' : 'authored + missing') : 'generic/fallback';
  const model = w.prefabPath ? `${w.loadVia || 'resources'}:${w.prefabPath}` : 'missing';
  const state = w.visualReadiness || 'Unreviewed';
  const evidence = w.visualEvidence || w.visualFailureReason || 'owner contact sheet required';
  out += `| ${esc(w.id)} | ${esc(icon)} | ${esc(model)} | ${esc(state)} | ${esc(evidence)} |\n`;
}
out += '\n## Armor\n\n| id | icon | applied stats | authored state | evidence/failure |\n|---|---|---|---|---|\n';
for (const a of armor) {
  const icon = a.iconPath ? (existsResource(a.iconPath) ? 'authored + found' : 'authored + missing') : 'missing';
  const stats = `def=${a.defense || 0}; hp=${a.hpBonus || 0}`;
  const state = a.visualReadiness || 'Unreviewed';
  const evidence = a.visualEvidence || a.visualFailureReason || 'owner 2D identity review required';
  out += `| ${esc(a.id)} | ${esc(icon)} | ${esc(stats)} | ${esc(state)} | ${esc(evidence)} |\n`;
}
const target = path.join(root, 'docs/GEAR_VISUAL_READINESS_2026-08-22.md');
fs.writeFileSync(target, out, 'utf8');

let curation = '# Weapon identity curation — 2026-08-22\n\n';
curation += 'Mechanics-first inventory. Blank effects/VFX are intentional stats-only baselines, not missing promises. '; 
curation += 'A semantic VFX verb is sellable only when the owner-authored registry resolves it.\n\n';
curation += '| id | final name | subtitle | class/family/tier | element | effect parameters | maker mark | VFX verbs | price input | readiness |\n';
curation += '|---|---|---|---|---|---|---|---|---|---|\n';
for (const w of weapons) {
  const family = `${w.job || 'any'}/${w.category || 'weapon'}/${w.rarity || 'common'}`;
  const effect = w.effectKind
    ? `${w.effectKind}: chance=${w.effectChance || 0}, damagePct=${w.effectDamagePct || 0}, duration=${w.effectDurationSeconds || 0}, stacks=${w.effectMaxStacks || 0}, cooldown=${w.effectCooldownSeconds || 0}`
    : w.ammoEffect ? `${w.ammoEffect}: dps=${w.ammoDps || 0}, duration=${w.ammoSeconds || 0}, slowPct=${w.ammoSlowPct || 0}` : 'none';
  const verbs = [w.vfxHeld, w.vfxAttack, w.vfxHit, w.vfxProc].filter(Boolean).join(', ') || 'none';
  const priceInput = `power=${w.damageMult || 1}; reach=${w.reach || 0}; set=${w.setId || 'none'}`;
  curation += `| ${esc(w.id)} | ${esc(w.name || w.id)} | ${esc(w.subtitle || '')} | ${esc(family)} | ${esc(w.element || 'physical')} | ${esc(effect)} | ${esc(w.makersMark || '')} | ${esc(verbs)} | ${esc(priceInput)} | ${esc(w.visualReadiness || 'Unreviewed')} |\n`;
}
const curationTarget = path.join(root, 'docs/GEAR_WEAPON_CURATION_2026-08-22.md');
fs.writeFileSync(curationTarget, curation, 'utf8');
console.log(`wrote ${path.relative(root, target)} and ${path.relative(root, curationTarget)} (${weapons.length} weapons, ${armor.length} armor)`);
