#!/usr/bin/env python3
"""
home_build.py - generate HOME.html (the wiki-style start page over the doc lake) FROM the repo.

WO-943: ~1090 markdown files had no navigable entry point. This page is the START link for
every seat and for the owner - one click to the rules, the architectural canon, the north
star, the board, the component catalogs, the asset-organization registries, and the
operator docs. Sibling of tools/board_build.py and follows the same law:

    THE REPO IS THE SOURCE OF TRUTH; THIS PAGE IS A DERIVED VIEW. Never hand-edit it.

    python tools/home_build.py        # ~2 s - regenerate HOME.html + the two org pages

Reads:  the load-bearing doc set (titles harvested live, never copied bodies),
        CANON_GROUND_TRUTH_*.md (newest-by-date resolved AT GENERATION TIME),
        docs/MASTER_CATALOG/*.md (first heading harvested as the one-liner),
        Assets/Resources/VFX/** and the audio tree (walked this run, source-cited).
Writes: HOME.html (repo root)
        docs/reference/VFX_ORGANIZATION.md    (generated registry - never hand-maintained)
        docs/reference/SOUND_ORGANIZATION.md  (generated registry - never hand-maintained)

DEAD-LINK GATE (WO-943 binding): any link target that does not exist on disk FAILS the
run (prints the misses, exits 1) - a renamed doc breaks this build instead of silently
404ing the owner.
"""
import os, re, glob, html, datetime, sys
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "HOME.html")
REF_DIR = os.path.join(ROOT, "docs", "reference")
VFX_PAGE = os.path.join(REF_DIR, "VFX_ORGANIZATION.md")
SOUND_PAGE = os.path.join(REF_DIR, "SOUND_ORGANIZATION.md")

STAMP = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
GEN_BANNER = ("> **GENERATED by `tools/home_build.py` on {stamp} - DO NOT HAND-EDIT.** "
              "This registry is rebuilt from the actual tree on every run "
              "(`python tools/home_build.py`); a hand edit is destroyed by the next run. "
              "Every fact below carries the source path it was read from this run.")


# ── shared harvesting helpers ─────────────────────────────────────────────────

def read_text(relpath, limit=20000):
    try:
        with open(os.path.join(ROOT, relpath), encoding="utf-8", errors="replace") as f:
            return f.read(limit)
    except OSError:
        return ""

def first_heading(relpath):
    """Harvest a file's first markdown heading (or first non-blank line) - a TITLE,
    never a copied body. Returns '' when unreadable."""
    text = read_text(relpath, 4000)
    m = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    if m:
        return re.sub(r"[*`]", "", m.group(1)).strip()
    for line in text.splitlines():
        line = line.strip()
        if line and not line.startswith((">", "<", "|", "-", "```")):
            return re.sub(r"[*`#]", "", line).strip()[:140]
    return ""

def newest_ground_truth():
    """Resolve the CURRENT canon anchor NEWEST-BY-DATE at generation time (never a
    hardcoded filename - the stale-copy lesson). Root-level only; archived ones are frozen."""
    best, best_date = None, ""
    for p in glob.glob(os.path.join(ROOT, "CANON_GROUND_TRUTH_*.md")):
        m = re.search(r"CANON_GROUND_TRUTH_(\d{4}-\d{2}-\d{2})\.md$", os.path.basename(p))
        if m and m.group(1) > best_date:
            best_date, best = m.group(1), os.path.basename(p)
    return best, best_date

def walk_counts(relpath):
    """Non-.meta file count + per-extension Counter for a folder subtree (walked this run)."""
    base = os.path.join(ROOT, relpath)
    exts = Counter()
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames.sort()
        for fn in sorted(filenames):
            if fn.endswith(".meta"):
                continue
            ext = os.path.splitext(fn)[1].lower() or "(none)"
            exts[ext] += 1
    return sum(exts.values()), exts

def fmt_exts(exts):
    return ", ".join(f"{e} x{n}" for e, n in sorted(exts.items(), key=lambda kv: (-kv[1], kv[0])))


# ── the two generated asset-organization registries (WO-943 §2.6) ─────────────

def build_vfx_page():
    """docs/reference/VFX_ORGANIZATION.md - how the VFX are organized, read from the
    actual tree this run (audit-outputs-as-known-dictionaries: source-cited facts)."""
    vfx_rel = "Assets/Resources/VFX"
    vfx_abs = os.path.join(ROOT, vfx_rel)
    lines = ["# VFX Organization - generated registry (WO-943)", "",
             GEN_BANNER.format(stamp=STAMP), ""]

    if not os.path.isdir(vfx_abs):
        lines.append(f"**`{vfx_rel}/` NOT FOUND on disk this run.**")
        return "\n".join(lines) + "\n", 0, 0

    top = sorted(d for d in os.listdir(vfx_abs)
                 if os.path.isdir(os.path.join(vfx_abs, d)))
    catalogs = sorted(f for f in os.listdir(vfx_abs)
                      if f.endswith(".asset"))
    total_files = 0

    lines += [f"## Runtime VFX root: `{vfx_rel}/`",
              "",
              f"Source: directory walk of `{vfx_rel}/` this run. Counts exclude `.meta` files.",
              "",
              "| Folder | Files | By type |",
              "|---|---|---|"]
    for d in top:
        n, exts = walk_counts(f"{vfx_rel}/{d}")
        total_files += n
        lines.append(f"| `{vfx_rel}/{d}/` | {n} | {fmt_exts(exts) or '-'} |")

    lines += ["", f"## Catalog assets at the VFX root (`{vfx_rel}/*.asset`)", "",
              "Names only, read from disk this run - open the asset in Unity for contents.", ""]
    for c in catalogs:
        lines.append(f"- `{vfx_rel}/{c}`")

    shared_rel = f"{vfx_rel}/_Shared"
    if os.path.isdir(os.path.join(ROOT, shared_rel)):
        lines += ["", f"## `_Shared` breakdown (`{shared_rel}/`)", "",
                  "| Subfolder | Files | By type |", "|---|---|---|"]
        for d in sorted(os.listdir(os.path.join(ROOT, shared_rel))):
            if os.path.isdir(os.path.join(ROOT, shared_rel, d)):
                n, exts = walk_counts(f"{shared_rel}/{d}")
                lines.append(f"| `{shared_rel}/{d}/` | {n} | {fmt_exts(exts) or '-'} |")

    if os.path.isfile(os.path.join(REF_DIR, "VFX_AUDIO_WIRING_MAP.md")):
        lines += ["", "## Related",
                  "", "- [VFX_AUDIO_WIRING_MAP.md](VFX_AUDIO_WIRING_MAP.md) - "
                      "the VFX/audio key-to-hook wiring map (`docs/reference/VFX_AUDIO_WIRING_MAP.md`)"]
    return "\n".join(lines) + "\n", len(top), total_files


def parse_enum(relpath, name):
    """Enum member names read from the actual C# source (never from a doc)."""
    text = read_text(relpath, 60000)
    m = re.search(r"enum\s+" + re.escape(name) + r"\s*\{", text)
    if not m:
        return []
    depth, i = 1, m.end()
    start = i
    while i < len(text) and depth:
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
        i += 1
    body = text[start:i - 1]
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    body = re.sub(r"//[^\n]*", "", body)
    body = re.sub(r"\[[^\]]*\]", "", body)
    vals = []
    for part in body.split(","):
        mm = re.match(r"\s*([A-Za-z_]\w*)", part)
        if mm:
            vals.append(mm.group(1))
    return vals


def find_sources(filename):
    """Locate ALL .cs sources of this name under Assets/_Modules by walk (the CLAUDE.md
    §5 table is a convenience subset and has mis-stated homes before - the tree is the
    authority; MusicTrack.cs genuinely exists TWICE, in Core and in Audio)."""
    base = os.path.join(ROOT, "Assets", "_Modules")
    hits = []
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames.sort()
        if filename in filenames:
            hits.append(os.path.relpath(os.path.join(dirpath, filename), ROOT).replace(os.sep, "/"))
    return sorted(hits)


def parse_namespace(relpath):
    m = re.search(r"^\s*namespace\s+([\w.]+)", read_text(relpath, 8000), re.MULTILINE)
    return m.group(1) if m else "?"


def build_sound_page():
    """docs/reference/SOUND_ORGANIZATION.md - how the sounds are organized: enums read
    from the C# source, clip homes read from disk, all source-cited."""
    lines = ["# Sound Organization - generated registry (WO-943)", "",
             GEN_BANNER.format(stamp=STAMP), ""]

    sfx_srcs = find_sources("SfxId.cs")
    music_srcs = find_sources("MusicTrack.cs")
    lib_srcs = find_sources("SfxClipLibrary.cs")
    lib_src = lib_srcs[0] if lib_srcs else None
    sfx_src = sfx_srcs[0] if sfx_srcs else None
    sfx_vals = parse_enum(sfx_src, "SfxId") if sfx_src else []

    lines += [f"## `SfxId` - {len(sfx_vals)} named SFX events",
              "",
              f"Source: enum parsed from `{sfx_src or 'NOT FOUND under Assets/_Modules'}` "
              f"(namespace `{parse_namespace(sfx_src) if sfx_src else '?'}`) this run. "
              "The key to `AudioService.PlaySfxAtPosition` and `VFXManager.VfxToSfx()`.",
              ""]
    lines += [f"- `{v}`" for v in sfx_vals]

    # MusicTrack genuinely exists as TWO DISTINCT ENUMS (verified from the tree this run):
    # DeNelle.Core.Audio.MusicTrack (the cross-module key) and DeNelle.Audio.MusicTrack
    # (the mix-registry enum). A registry that silently picked one would be the exact
    # duplicated-state lie this page exists to prevent - list both, namespace-cited.
    n_music_total = 0
    lines += ["", f"## `MusicTrack` - {len(music_srcs)} enum(s) of this name in the tree", ""]
    if not music_srcs:
        lines.append("NOT FOUND under `Assets/_Modules` this run.")
    for src in music_srcs:
        vals = parse_enum(src, "MusicTrack")
        n_music_total += len(vals)
        lines += [f"### `{parse_namespace(src)}.MusicTrack` - {len(vals)} values",
                  "",
                  f"Source: enum parsed from `{src}` this run.",
                  ""]
        lines += [f"- `{v}`" for v in vals]
        lines.append("")

    lines += ["## `SfxClipLibrary` - the SfxId-to-AudioClip mapping",
              "",
              f"Source: `{lib_src or 'NOT FOUND under Assets/_Modules'}` (ScriptableObject; one Entry row "
              "per `SfxId`, null Clip = silent no-op at runtime). Create via "
              "`Assets > Create > Defenders/Audio/SFX Clip Library`; assigned to "
              "`AudioService._sfxLibrary`.", ""]

    lines += ["## Where clips live on disk", "",
              "Source: directory walks this run. Counts exclude `.meta` files.", "",
              "| Folder | Files | By type |", "|---|---|---|"]
    for rel in ["Assets/Audio", "Assets/Resources/Audio", "Assets/Resources/Sfx"]:
        if os.path.isdir(os.path.join(ROOT, rel)):
            n, exts = walk_counts(rel)
            lines.append(f"| `{rel}/` | {n} | {fmt_exts(exts) or '-'} |")
        else:
            lines.append(f"| `{rel}/` | - | NOT FOUND this run |")

    audio_abs = os.path.join(ROOT, "Assets", "Audio")
    if os.path.isdir(audio_abs):
        lines += ["", "### `Assets/Audio/` subfolders", ""]
        for d in sorted(os.listdir(audio_abs)):
            if os.path.isdir(os.path.join(audio_abs, d)):
                n, exts = walk_counts(f"Assets/Audio/{d}")
                lines.append(f"- `Assets/Audio/{d}/` - {n} file(s): {fmt_exts(exts) or '-'}")

    sfx_dir = os.path.join(ROOT, "Assets", "Resources", "Sfx")
    if os.path.isdir(sfx_dir):
        clips = sorted(f for f in os.listdir(sfx_dir)
                       if not f.endswith(".meta") and os.path.isfile(os.path.join(sfx_dir, f)))
        lines += ["", "### `Assets/Resources/Sfx/` clip files", ""]
        lines += [f"- `Assets/Resources/Sfx/{c}`" for c in clips]

    return "\n".join(lines) + "\n", len(sfx_vals), n_music_total


# ── HOME.html sections (WO-943 §2 - titles + one-liners + links, NEVER bodies) ─

def build_sections():
    gt_file, gt_date = newest_ground_truth()

    def entry(path, title, desc):
        return {"path": path, "title": title, "desc": desc}

    catalogs = [entry("docs/MASTER_CATALOG.md", "Master Catalog (hub)",
                      "The exhaustive file-by-file SME catalog - architecture map + stale/risk ledger. "
                      "Mandatory first read before touching any area.")]
    for p in sorted(glob.glob(os.path.join(ROOT, "docs", "MASTER_CATALOG", "*.md"))):
        rel = "docs/MASTER_CATALOG/" + os.path.basename(p)
        area = os.path.basename(p)[:-3]
        catalogs.append(entry(rel, area, first_heading(rel) or "per-area catalog"))

    sections = [
        ("The rules", "rules", "Binding on every seat, every session. RULES.md (WO-938) is the index; "
                               "the pointed-at docs are the authority.", [
            entry("RULES.md", "RULES.md", "The one page - every binding rule as one checkable line + "
                                          "a pointer to the doc that owns it."),
            entry("CLAUDE.md", "CLAUDE.md", "Agent rules & project memory - read by every agent before "
                                            "work; §15 = canon maintenance."),
            entry("PREFLIGHT_GATE.md", "Preflight gate", "The YES-plus-proof checklist answered before "
                                                         "touching any code or debugging."),
            entry("SESSION_CANON_LOADER.md", "Session canon loader", "The at-a-glance SME primer that "
                                                                    "boots a session (core rules + current state + key files)."),
        ]),
        ("Architectural canon", "canon", "The ruled architecture set. Per-area *_ARCHITECTURE.md "
                                         "deep-dives are reached THROUGH the hub, not listed flat.", [
            entry("docs/ARCHITECTURE.md", "Architecture hub", "THE single authoritative hub (HP B2B "
                                                              "lens, assembly map, world/scene, data, save, build mode) - indexes every deep-dive."),
            entry("docs/ARCHITECTURE_PRINCIPLES.md", "Architecture principles", "The owner's HP B2B "
                                                                                "law - bounded contexts, presentation never touches the objects, right-not-easy."),
        ]),
        ("North star", "northstar", "Where we are going, and what is CURRENTLY true. The ground-truth "
                                    "anchor below is resolved newest-by-date at generation time.", [
            entry("docs/COMBAT_PIVOT_NORTHSTAR.md", "Combat pivot north star",
                  "The Single-Knight pivot - supersedes the Blink/party-of-4 canon."),
            entry(gt_file or "CANON_GROUND_TRUTH_MISSING.md", f"Canon ground truth ({gt_date or '?'})",
                  "The single live anchor of current reality - newest dated anchor wins; "
                  "all earlier ones are frozen."),
            entry("KEY_FACTS.md", "Key facts", "The living fact sheet + north-star state, "
                                               "updated in place."),
        ]),
        ("The board", "board", "The live work-order board - GENERATED from WorkOrders/*.md "
                               "(python tools/board_build.py). The repo is the data; the board is a view.", [
            entry("BOARD.html", "BOARD.html", "Every work order bucketed Ready/Blocked/Spec/Done/Closed "
                                              "with search + filters. Regenerate before any read."),
        ]),
        ("Component catalogs", "catalogs", "docs/MASTER_CATALOG.md + its per-area pages - verified "
                                           "from the actual code, not comments.", catalogs),
        ("Asset organization", "assets", "How the VFX and sounds are organized - generated registries, "
                                         "source-cited from the actual tree on every run (WO-943 §2.6).", [
            entry("docs/reference/VFX_ORGANIZATION.md", "VFX organization",
                  "Generated registry: the Resources/VFX folder taxonomy, counts by type, "
                  "catalog assets, the _Shared breakdown."),
            entry("docs/reference/SOUND_ORGANIZATION.md", "Sound organization",
                  "Generated registry: SfxId + MusicTrack enum values read from source, "
                  "SfxClipLibrary, where clips live on disk."),
            entry("docs/reference/VFX_AUDIO_WIRING_MAP.md", "VFX/audio wiring map",
                  "The key-to-hook wiring map for VFX and audio events."),
        ]),
        ("Operator docs", "operator", "How this project is actually run, day to day.", [
            entry("docs/HANDOVER.md", "Handover", "The single operator's manual a new session reads "
                                                  "first - how we work + the build/gate/bake cycle + resume points."),
            entry("docs/TICKET_PIPELINE.md", "Ticket pipeline", "The role-separated QA -> CLI -> PO "
                                                                "bug pipeline (binding)."),
            entry("docs/BOARD.md", "Board protocol", "How the derived board works - status vocabulary, "
                                                     "scope, the --check gate."),
            entry("docs/UI_PLAYBOOK.md", "UI playbook", "Read before adding or changing any screen, "
                                                        "panel, HUD element or overlay - 15 practices, each citing the defect it prevents."),
            entry("docs/INSTRUMENTATION_STANDARD.md", "Instrumentation standard",
                  "How code is written observable-first - FlowTrace/Guard/regression authoring "
                  "(the method behind CLAUDE.md §12)."),
            entry("docs/README.md", "Docs index", "The category index of docs/ - find your category, "
                                                  "don't grep blind."),
            entry("PROJECT_INDEX.md", "Project index", "The root-file map - living docs vs frozen "
                                                       "dated ledgers."),
            entry("START_HERE.md", "Start here", "The boot sequence a fresh CLI session follows."),
        ]),
    ]
    return sections


def check_links(sections):
    """The dead-link gate: every linked target must exist on disk, or the build FAILS."""
    missing = []
    for _, _, _, entries in sections:
        for e in entries:
            if not os.path.exists(os.path.join(ROOT, e["path"])):
                missing.append(e["path"])
    return missing


def build_home_html(sections):
    def section_html(title, sid, blurb, entries):
        rows = "\n".join(
            f'<div class="entry"><a href="{html.escape(e["path"])}">{html.escape(e["title"])}</a>'
            f'<span class="desc">{html.escape(e["desc"])}</span></div>'
            for e in entries)
        return (f'<div class="card" id="{sid}"><h2>{html.escape(title)}</h2>'
                f'<p class="blurb">{html.escape(blurb)}</p>{rows}</div>')

    cards = "\n".join(section_html(*s) for s in sections)
    nav = " ".join(f'<a href="#{sid}">{html.escape(title)}</a>'
                   for title, sid, _, _ in sections)

    return f"""<!DOCTYPE html><html><head><meta charset="utf-8">
<title>EoA Home - {STAMP}</title>
<style>
 body{{background:#14151a;color:#ddd;font:14px/1.5 'Segoe UI',sans-serif;margin:0;padding:24px}}
 h1{{color:#e0b341;font-size:24px;margin:0 0 4px}}
 h2{{color:#e0b341;font-size:16px;margin:0 0 6px;border-bottom:1px solid #2a2c36;padding-bottom:6px}}
 .sub{{color:#888;margin-bottom:14px}} .sub b{{color:#bbb}}
 .nav{{margin-bottom:18px}} .nav a{{color:#7fa8d9;margin-right:14px;text-decoration:none}}
 .grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(430px,1fr));gap:16px}}
 .card{{background:#1e2027;border:1px solid #2c2e38;border-radius:10px;padding:16px 18px}}
 .blurb{{color:#888;font-size:12px;margin:0 0 10px}}
 .entry{{padding:5px 0;border-bottom:1px solid #24262e}}
 .entry:last-child{{border-bottom:0}}
 .entry a{{color:#e0b341;text-decoration:none;font-weight:600;white-space:nowrap}}
 .entry a:hover{{text-decoration:underline}}
 .desc{{color:#999;font-size:12px;display:block}}
</style></head><body>
<h1>Echoes of Elarion — Home</h1>
<div class="sub">Generated <b>{STAMP}</b> from the repo — the repo is the source of truth, this page
 is a derived view (WO-943). Regenerate: <b>python tools/home_build.py</b>. Dead links FAIL the
 generator, so every link below was live at generation time.</div>
<div class="nav">{nav}</div>
<div class="grid">
{cards}
</div>
</body></html>"""


# ── main ──────────────────────────────────────────────────────────────────────

def main():
    # 1. The two generated asset-organization registries FIRST (HOME links them).
    os.makedirs(REF_DIR, exist_ok=True)
    vfx_md, vfx_folders, vfx_files = build_vfx_page()
    with open(VFX_PAGE, "w", encoding="utf-8") as f:
        f.write(vfx_md)
    sound_md, n_sfx, n_music = build_sound_page()
    with open(SOUND_PAGE, "w", encoding="utf-8") as f:
        f.write(sound_md)

    # 2. Sections, then the dead-link gate BEFORE writing HOME.html.
    sections = build_sections()
    missing = check_links(sections)
    if missing:
        print(f"HOME_BUILD_FAIL {len(missing)} dead link(s) - a linked target does not exist on disk:")
        for m in missing:
            print(f"    MISSING {m}")
        return 1

    with open(OUT, "w", encoding="utf-8") as f:
        f.write(build_home_html(sections))

    n_links = sum(len(entries) for _, _, _, entries in sections)
    per = " ".join(f"{sid}:{len(entries)}" for _, sid, _, entries in sections)
    print(f"HOME.html written: {n_links} links, all live ({per}) + VFX_ORGANIZATION.md "
          f"({vfx_folders} folders, {vfx_files} files) + SOUND_ORGANIZATION.md "
          f"({n_sfx} SfxId, {n_music} MusicTrack values)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
